// Generated by services/dot-relay/generate-native.mjs; do not edit.
#if os(macOS)
import Foundation
struct DotInteractionEvent: Codable, Sendable {
    var relationId: String; var sequence: Int; var kind: String; var direction: String; var stage: String
    var targetRef: String?; var summary: String; var evidence: String; var receivedAt: Int
    var dictionary: [String: Any] {
        ["relationId": relationId, "sequence": sequence, "kind": kind, "direction": direction, "stage": stage,
         "targetRef": targetRef as Any? ?? NSNull(), "summary": summary, "evidence": evidence, "receivedAt": receivedAt]
    }
    var label: String {
        let target = targetRef.map { "Unverified target " + $0 } ?? "Unknown target"
        let edge = direction == "dot_to_agent" ? "Dot → " + target : target + " → Dot"
        return kind + " · " + stage + " · " + edge + " · Dot report"
    }
}
enum DotInteractionPolicy {
    static let rank: [String: Int] = ["requested": 0, "delivered": 1, "accepted": 2, "running": 3, "needs_attention": 3, "completed": 4, "failed": 4, "cancelled": 4]
    static let terminal = ["completed", "failed", "cancelled"]
    static func allows(_ prior: DotInteractionEvent?, _ next: DotInteractionEvent) -> Bool {
        guard rank[next.stage] != nil else { return false }
        guard let prior else { return true }
        return next.sequence > prior.sequence && next.kind == prior.kind && next.direction == prior.direction
            && next.targetRef == prior.targetRef && !terminal.contains(prior.stage)
            && (rank[next.stage] ?? -1) >= (rank[prior.stage] ?? Int.max)
    }
}
#endif
