// Generated by services/dot-relay/generate-native.mjs; do not edit.
enum DotLimits {
    static let bodyBytes = 32768
    static let headerBytes = 8192
    static let callbackResponseBytes = 8192
    static let callbackMs = 10000
    static let subscriptionMs = 86400000
    static let rotationMs = 300000
    static let requestMs = 1800000
    static let claimMs = 300000
    static let attempts = 5
    static let records = 1000
    static let connections = 16
    static let retentionMs = 604800000
    static let requestsPerMinute = 240
    static let interactionEvents = 16
    static let interactionSummaryCharacters = 240
    static let reportFreshMs = 180000
    static let completionReactionMs = 8000
    static let feedReports = 3
    static let contextCharacters = 8000
    static let reportCharacters = 4000
    static let reportKeys = 128
    static let callbackURLCharacters = 2048
    static let retryMaxMs = 60000
}
enum DotOAuthLimits {
    static let pending = 16
    static let records = 16384
    static let consentMs = 120000
    static let accessMs = 300000
    static let refreshMs = 2592000000
}
