// GENERATED by scripts/generate-usage-presentation.mjs. DO NOT EDIT.
// SSOT: shared/src/usage-presentation.ts
#pragma once
#include <cmath>
#include <cstdio>
#include <cstring>
#include <cctype>
namespace UsagePresentation {
static constexpr const char* Heading = "USAGE";
static constexpr const char* Providers[] = {"Claude","Codex","z.ai","Antigravity"};
inline bool lunaActive(float primary, float secondary, float reserve) { return reserve >= 0 && (primary >= 100 || secondary >= 100); }
// usageCreditsActive: balance is -1 when unknown, +INFINITY when unlimited.
inline bool creditsActive(float primary, float secondary, double balance) { return balance > 0 && (primary >= 100 || secondary >= 100); }
// formatCreditBalance: truncated, integer-only, "∞" (UTF-8) when unlimited.
inline void formatCreditBalance(double balance, char* out, size_t outLen) {
    if (!out || outLen == 0) return;
    if (std::isinf(balance) && balance > 0) { std::snprintf(out, outLen, "\xE2\x88\x9E"); return; }
    if (!(balance > 0)) { std::snprintf(out, outLen, "0"); return; }
    struct Unit { double divisor; const char* suffix; };
    static constexpr Unit units[] = {{1000000, "M"}, {1000, "K"}};
    for (const Unit& u : units) {
        if (balance < u.divisor) continue;
        const long long tenths = static_cast<long long>(std::floor(balance * 10 / u.divisor));
        if (tenths >= 1000 || tenths % 10 == 0) std::snprintf(out, outLen, "%lld%s", tenths / 10, u.suffix);
        else std::snprintf(out, outLen, "%lld.%lld%s", tenths / 10, tenths % 10, u.suffix);
        return;
    }
    if (balance >= 10) { std::snprintf(out, outLen, "%lld", static_cast<long long>(std::floor(balance))); return; }
    const long long tenths = static_cast<long long>(std::floor(balance * 10));
    if (tenths % 10 == 0) std::snprintf(out, outLen, "%lld", tenths / 10);
    else std::snprintf(out, outLen, "%lld.%lld", tenths / 10, tenths % 10);
}
inline bool startsWith(const char* name, const char* prefix) {
    while (*name == ' ') ++name;
    while (*prefix) { if (std::tolower(static_cast<unsigned char>(*name++)) != std::tolower(static_cast<unsigned char>(*prefix++))) return false; }
    return true;
}
inline int subscriptionProvider(const char* name) {
    if (startsWith(name, "Claude")) return 0;
    if (startsWith(name, "ChatGPT") || startsWith(name, "Codex")) return 1;
    if (startsWith(name, "GLM Coding Plan") || startsWith(name, "z.ai")) return 2;
    if (startsWith(name, "Google AI") || startsWith(name, "Antigravity") || startsWith(name, "AGY")) return 3;
    return -1;
}
// usageSubscriptionTier: the subscription name without its provider prefix.
inline void subscriptionTier(const char* name, char* out, size_t outLen) {
    if (!out || outLen == 0) return;
    out[0] = '\0';
    if (!name) return;
    while (*name == ' ') ++name;
    static constexpr const char* prefixes[] = {"Claude","ChatGPT","Codex","GLM Coding Plan","z.ai","Google AI","Antigravity","AGY"};
    const char* tail = nullptr;
    for (const char* prefix : prefixes) if (startsWith(name, prefix)) { tail = name + std::strlen(prefix); break; }
    if (tail) {
        // Separators: " ·:-" (UTF-8 middle dot is two bytes).
        for (;;) {
            if (*tail && std::strchr(" :-", *tail)) { ++tail; continue; }
            if (static_cast<unsigned char>(tail[0]) == 0xC2 && static_cast<unsigned char>(tail[1]) == 0xB7) { tail += 2; continue; }
            break;
        }
    }
    // A prefix-only name ("Claude") has no tier: leave it empty.
    const char* src = tail ? tail : name;
    size_t n = std::strlen(src);
    while (n && src[n - 1] == ' ') --n;
    if (n >= outLen) n = outLen - 1;
    std::memcpy(out, src, n);
    out[n] = '\0';
}
}
