"""Bring the finished head blockout into the mermaid builder (v19).

The head is authored in `hermes-head/` (seed + edits.json + fringe/locks/headset
steps, see NOTES.md) and regenerated by `sh run.sh <dir>` into
`hermes-head-blockout.blend`. This module loads that file into the builder's
scene and converts it to the builder's head frame. It then names and parents
the parts so the schema-2 app contract (HermesMermaid.swift) is unchanged:
- the skin is the `face` mesh, which the decals and the app test look up by name;
- the flicked locks hang from the existing `hermes_hair_left/right` sway joints.
  In v18 those joints were empty; now the app's sway moves real locks.

Frame: the blockout is Z-up with 1 unit = 100 px of the head-study sheet and
the face toward -Y. The builder's head frame is Y-up metres with the face
toward +Z. The two are tied by the face sheet: the bang line (z 1.86) maps to
HEM_Y 0.020, and the chin (z -0.14) maps to CHIN_Y -0.210, so
k = 0.230 / 2.00 = 1 / 8.696 m per unit.
Naming note: the builder's "left" is the viewer's left (x < 0). That is HER
right, which the blockout calls *_R.
"""
import math, os, sys
import bpy, bmesh
from mathutils import Vector

HERE = os.path.dirname(os.path.abspath(__file__))
BLEND = os.path.join(HERE, "hermes-head-blockout.blend")
K = 1 / 8.696
HEM_Z, HEM_Y = 1.86, 0.020
NECK_R = 0.435         # blockout units (0.050 m): the visible neck is the painted face neck (concept: ~42% of face width), just outside the body
sys.path.insert(0, HERE)
from facets import facet_mass


def to_head(p):
    return Vector((p.x * K, (p.z - HEM_Z) * K + HEM_Y, -p.y * K))


def _load():
    with bpy.data.libraries.load(BLEND, link=False) as (src, dst):
        dst.objects = [n for n in src.objects if n.startswith(("hermes_head_cage", "hermes_hair_cage", "hermes_hair_planes", "hermes_lock_", "hermes_headset_"))]
    for ob in dst.objects:
        bpy.context.scene.collection.objects.link(ob)
    return {ob.name: ob for ob in dst.objects}


def _neck(me):
    """Shape the blockout's neck rings (11, 12) into the visible neck: an ellipse
    as wide as the front sheet's neck (half-width ~0.53) but shallower, with
    its front where the profile sheet has it (y ~ -0.28), 2026-10-02."""
    R = me.attributes["ring"].data
    RX, RY, CY = 0.53, 0.38, 0.10
    for v in me.vertices:
        if R[v.index].value in (11, 12):
            dx, dy = v.co.x, v.co.y - CY
            import math as _m
            a = _m.atan2(dy / RY, dx / RX)
            v.co.x, v.co.y = RX * _m.cos(a), CY + RY * _m.sin(a)


def _jaw_crease(me):
    """Crease the jawline loop (ring 10) and the neck junction (ring 11).

    The concept's jaw is an edge: lit cheek planes turn into a shaded underside,
    and the neck is a separate shaded cylinder. Uncreased, subdivision rounded
    both loops into one balloon from chin to neck (a double-chin gradient).
    """
    R, C = me.attributes["ring"].data, me.attributes["col"].data
    attr = me.attributes.get("crease_edge") or me.attributes.new("crease_edge", "FLOAT", "EDGE")
    for e in me.edges:
        a, b = e.vertices
        ra, rb = R[a].value, R[b].value
        if ra == rb == 10:
            attr.data[e.index].value = 0.45   # softer: a hard jaw edge made a cut-out shadow
        elif ra == rb == 11:
            attr.data[e.index].value = 0.3


def _bake(src, name, mat, parent, smooth, origin=Vector()):
    dg = bpy.context.evaluated_depsgraph_get()
    me = bpy.data.meshes.new_from_object(src.evaluated_get(dg))
    for v in me.vertices:
        v.co = to_head(v.co) - origin
    me.materials.clear(); me.materials.append(mat)
    for p in me.polygons:
        p.use_smooth = smooth
    # the frame change (Y-forward -> Z-forward) is a rotation, so winding stays outward
    me.name = name
    o = bpy.data.objects.new(name, me)
    bpy.context.scene.collection.objects.link(o)
    o.parent = parent          # vertices are already relative to the parent joint
    return o


def build(head, mats, joint):
    """Create face / hair / locks / headset under `head`. Returns the face object.

    mats: dict with 'skin', 'hair', 'white', 'dot'. joint: the builder's joint().
    """
    src = _load()
    _neck(src["hermes_head_cage"].data)
    for m in src["hermes_head_cage"].modifiers:
        if m.type == "SUBSURF":
            m.levels = m.render_levels = 3      # fine enough for the nose form
    _jaw_crease(src["hermes_head_cage"].data)
    face = _bake(src["hermes_head_cage"], "face", mats["skin"], head, True)
    # nose form + painted shading measured from the concepts (face_paint.py)
    import face_paint
    from face_v2 import F as FV
    # face_paint.eye_planes(face, FV)   # tried 2026-10-02: the flat socket stood proud of the cheek and made the profile eye larger; not used
    face_paint.nose_form(face, FV)
    base = mats["skin"].node_tree.nodes["Principled BSDF"].inputs["Base Color"].default_value
    srgb = [c * 12.92 if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055 for c in base[:3]]
    cage = src["hermes_head_cage"].data
    Rr, Cc = cage.attributes["ring"].data, cage.attributes["col"].data
    jaw = sorted((abs(to_head(v.co).x), to_head(v.co).y) for v in cage.vertices
                 if Rr[v.index].value == 10 and Cc[v.index].value in (0, 1, 2, 3))
    face_paint.uv_and_material(face, mats["skin"], face_paint.paint(face, FV, srgb, jaw))
    # A skin-coloured backing 1.5 mm behind the face front. RealityKit showed
    # isolated single-pixel gaps in the face around the nose (no hole in the
    # mesh: Blender with back-face culling shows none). They let the dark hair
    # behind show through as black specks; the backing makes any gap read as skin.
    import bmesh
    bm = bmesh.new(); bm.from_mesh(face.data); bm.normal_update()
    bmesh.ops.delete(bm, geom=[f for f in bm.faces if f.calc_center_median().z < 0.03], context="FACES")
    for v in bm.verts:
        v.co -= v.normal * 0.0015
    me = bpy.data.meshes.new("face_backing"); bm.to_mesh(me); bm.free()
    me.materials.append(mats["skin"])
    for p in me.polygons:
        p.use_smooth = True
    back = bpy.data.objects.new("face_backing", me)
    bpy.context.scene.collection.objects.link(back); back.parent = head

    hair = src["hermes_hair_cage"]
    for m in hair.modifiers:
        if m.type == "SUBSURF":
            m.levels = m.render_levels = 0
    planes = src.get("hermes_hair_planes")
    if planes is not None:
        # hand-laid lock planes are the visible hair; the sculpted cage is the
        # dark under-layer that fills the gaps between locks
        _bake(planes, "portrait_bob", mats["hair"], head, False)
        # recess the under-layer: the planes are chords across the curved cage,
        # and a cage at full size pokes through mid-plane as dark diamonds
        d = hair.modifiers.new("recess", "DISPLACE"); d.strength = -0.16; d.mid_level = 0.0
        hair.modifiers.move(len(hair.modifiers) - 1, 0)
        _bake(hair, "hair_under", mats.get("under", mats["hair"]), head, False)
    else:
        facet_mass(hair.data)
        # (smooth-shading the dome-to-fringe band was tried 2026-10-02: it read
        # as a glossy plastic helmet and lost the faceted style; kept flat)
        # (a brighter second material on the fringe front was tried 2026-10-02:
        # it read as a separate blue band with a harder edge; kept one material)
        _bake(hair, "portrait_bob", mats["hair"], head, False)

    # sway joints at the flick roots; the flick locks hang from them
    locks = [o for n, o in src.items() if n.startswith("hermes_lock_")]
    for o in locks:
        for m in o.modifiers:
            if m.type == "SUBSURF":
                # faceted, like the rest of the hair (a smooth-shaded subdivided
                # curl read as a tube/tentacle next to the faceted bob, 2026-10-02)
                m.levels = m.render_levels = 0
    pivots = {}
    for label, side in (("left", "_R"), ("right", "_L")):
        roots = [o for o in locks if o.name.startswith(("hermes_lock_up" + side, "hermes_lock_lo" + side))]
        if roots:
            c = sum((to_head(o.data.vertices[0].co) for o in roots), Vector()) / len(roots)
            pivots[label] = (joint("hermes_hair_" + label, head, tuple(c)), [o.name for o in roots])
    for o in locks:
        owner = next(((j, j.location.copy()) for j, names in pivots.values() if o.name in names), (head, Vector()))
        _bake(o, "hair_flick_" + o.name[len("hermes_lock_"):], mats["hair"], owner[0], False, owner[1])
    for label in ("left", "right"):     # the contract needs both joints even without locks
        if label not in pivots:
            joint("hermes_hair_" + label, head, (0, 0.1, 0))

    for n, o in src.items():
        if n.startswith("hermes_headset_"):
            mat = mats["dot"] if n.endswith("dot") else mats["white"]
            _bake(o, "headset_" + n[len("hermes_headset_"):], mat, head, n.endswith("band"))

    for o in src.values():
        bpy.data.objects.remove(o, do_unlink=True)
    return face
