"""Render a fixed 1-bit TRMNL plate; no temporal dithering or runtime allocation."""
from pathlib import Path
from array import array
import bpy

ROOT = Path(__file__).resolve().parents[2]
bpy.ops.wm.open_mainfile(filepath=str(ROOT / 'assets/terrarium/living-aquarium.blend'))
s = bpy.data.scenes['AgentDeck Living Aquarium']
bpy.context.window.scene = s
# Paper gets a quiet white field, not the color scene's banded water gradient.
for obj in s.objects:
    if any(name in obj.name for name in ['Sand bed', 'Quiet water backdrop', 'Seamless substrate']):
        mat = bpy.data.materials.new('Paper field')
        mat.use_nodes = True
        nodes = mat.node_tree.nodes
        nodes.clear()
        output = nodes.new('ShaderNodeOutputMaterial')
        emission = nodes.new('ShaderNodeEmission')
        emission.inputs['Color'].default_value = (1, 1, 1, 1)
        mat.node_tree.links.new(emission.outputs[0], output.inputs['Surface'])
        obj.data.materials.clear()
        obj.data.materials.append(mat)
# A paper-specific material pass preserves silhouettes under bright scene lighting.
for mat in bpy.data.materials:
    if mat.name.startswith('Paper field') or not mat.use_nodes:
        continue
    value = .16 if mat.name in {'pearl teal', 'fin', 'warm lower tail'} else .35
    if mat.name == 'eye': value = .005
    if mat.name == 'lateral silver': value = .75
    if 'leaves' in mat.name: value = .42
    if mat.name == 'River stone': value = .68
    nodes = mat.node_tree.nodes
    nodes.clear()
    output = nodes.new('ShaderNodeOutputMaterial')
    emission = nodes.new('ShaderNodeEmission')
    emission.inputs['Color'].default_value = (value, value, value, 1)
    mat.node_tree.links.new(emission.outputs[0], output.inputs['Surface'])
s.render.resolution_x = 800
s.render.resolution_y = 384
s.render.resolution_percentage = 100
s.cycles.samples = 32
s.view_settings.view_transform = "Standard"
s.frame_set(190)
(ROOT / 'dist/aquarium-study').mkdir(parents=True, exist_ok=True)
s.render.filepath = str(ROOT / 'dist/aquarium-study/paper-source.png')
bpy.ops.render.render(write_still=True)
im = bpy.data.images.load(s.render.filepath, check_existing=False)
p = array('f', [0]) * (800 * 384 * 4)
im.pixels.foreach_get(p)
bayer = ((0, 8, 2, 10), (12, 4, 14, 6), (3, 11, 1, 9), (15, 7, 13, 5))
packed = bytearray(800 * 384 // 8)
for y in range(384):
    for x in range(800):
        i = ((383-y) * 800+x) * 4
        gray = min(1, (p[i]*.2126+p[i+1]*.7152+p[i+2]*.0722) * 1.05)
        black = gray < (bayer[y%4][x%4]+.5)/16
        if black: packed[y*100+x//8] |= 1 << (7-x%8)
        value = 0.0 if black else 1.0
        p[i:i+4] = array('f', [value, value, value, 1])
im.pixels.foreach_set(p)
im.filepath_raw = str(ROOT / 'assets/terrarium/paper-aquarium.png')
im.save()
header = ROOT / 'esp32/src/ui/eink/paper_aquarium_generated.h'
lines = ['// Generated by assets/terrarium/export-paper-aquarium.py; 800x384, black bit=1.',
         '#pragma once', '#include <stdint.h>',
         'static const uint8_t PAPER_AQUARIUM[] PROGMEM = {']
lines += ['    '+', '.join('0x%02x' % b for b in packed[i:i+20])+',' for i in range(0,len(packed),20)]
lines += ['};', 'static_assert(sizeof(PAPER_AQUARIUM) == 38400, "Native 1-bit plate size");', '']
header.write_text('\n'.join(lines))
