// AUTO-GENERATED by scripts/generate-micro-glyphs.mjs — DO NOT EDIT.
// Canonical source: design/brand/*.svg. Regenerate with: pnpm generate-micro-glyphs
#pragma once
#include <cstdint>

namespace OfficialDotGlyphs {
constexpr int SIZE = 8;

// Offsets are in this namespace's master-mask coordinates. Immutable flash
// coverage is composited after the body; black RGB is an opaque paint operation.
struct FeatureLayer {
    uint8_t x, y, width, height;
    const uint8_t* alpha;
    uint8_t red, green, blue;
    bool monochromeInk;
    bool creatureMonochromeInk;
};

static const uint8_t CLAUDE_CODE[SIZE * SIZE] = {
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 85, 85, 85, 85, 85, 85, 0,
    0, 255, 217, 255, 255, 217, 255, 0,
    90, 255, 173, 255, 255, 173, 255, 90,
    175, 255, 255, 255, 255, 255, 255, 175,
    0, 216, 216, 177, 177, 216, 216, 0,
    0, 86, 86, 0, 0, 86, 86, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint8_t CLAUDE_CODE_FEATURE_0_A8[8] = {
    38, 0, 0, 38, 82, 0, 0, 82
};
constexpr int CLAUDE_CODE_FEATURE_COUNT = 1;
static const FeatureLayer CLAUDE_CODE_FEATURES[1] = {
    {2, 2, 4, 2, CLAUDE_CODE_FEATURE_0_A8, 0, 0, 0, false, true},
};

static const uint8_t CODEX[SIZE * SIZE] = {
    0, 12, 171, 240, 171, 111, 40, 0,
    12, 161, 255, 255, 255, 255, 246, 39,
    179, 250, 217, 255, 255, 255, 255, 111,
    246, 253, 94, 252, 255, 255, 255, 173,
    171, 254, 95, 251, 224, 221, 254, 242,
    105, 250, 210, 255, 157, 154, 247, 176,
    43, 243, 255, 255, 255, 255, 159, 12,
    0, 38, 109, 170, 242, 171, 12, 0,
};
static const uint8_t CODEX_FEATURE_0_A8[24] = {
    5, 38, 0, 0, 0, 0, 2, 161, 3, 0, 0, 0, 1, 160, 4, 31, 34, 1, 5, 45, 0, 98, 101, 8
};
constexpr int CODEX_FEATURE_COUNT = 1;
static const FeatureLayer CODEX_FEATURES[1] = {
    {1, 2, 6, 4, CODEX_FEATURE_0_A8, 255, 255, 255, false, false},
};

static const uint8_t OPEN_CODE[SIZE * SIZE] = {
    0, 56, 85, 85, 85, 85, 56, 0,
    0, 171, 255, 255, 255, 255, 171, 0,
    0, 171, 171, 0, 0, 171, 171, 0,
    0, 171, 171, 0, 0, 171, 171, 0,
    0, 171, 171, 0, 0, 171, 171, 0,
    0, 171, 171, 0, 0, 171, 171, 0,
    0, 171, 255, 255, 255, 255, 171, 0,
    0, 56, 85, 85, 85, 85, 56, 0,
};

constexpr int OPEN_CODE_FEATURE_COUNT = 0;
static const FeatureLayer OPEN_CODE_FEATURES[1] = {
    {0, 0, 0, 0, nullptr, 0, 0, 0, false, false},
};

static const uint8_t OPEN_CLAW[SIZE * SIZE] = {
    0, 9, 39, 16, 16, 39, 9, 0,
    0, 26, 201, 255, 255, 200, 26, 0,
    0, 179, 181, 204, 205, 186, 179, 0,
    168, 158, 255, 255, 255, 255, 160, 167,
    146, 182, 255, 255, 255, 255, 181, 146,
    0, 196, 255, 255, 255, 255, 194, 0,
    0, 38, 226, 255, 255, 226, 37, 0,
    0, 0, 20, 162, 161, 20, 0, 0,
};
static const uint8_t OPEN_CLAW_FEATURE_0_A8[4] = {
    76, 53, 50, 73
};
static const uint8_t OPEN_CLAW_FEATURE_1_A8[4] = {
    6, 9, 1, 15
};
constexpr int OPEN_CLAW_FEATURE_COUNT = 2;
static const FeatureLayer OPEN_CLAW_FEATURES[2] = {
    {2, 2, 4, 1, OPEN_CLAW_FEATURE_0_A8, 5, 8, 16, false, true},
    {2, 2, 4, 1, OPEN_CLAW_FEATURE_1_A8, 0, 229, 204, true, false},
};

static const uint8_t ANTIGRAVITY[SIZE * SIZE] = {
    0, 0, 4, 127, 129, 4, 0, 0,
    0, 0, 118, 255, 255, 121, 0, 0,
    0, 0, 221, 255, 255, 226, 1, 0,
    0, 45, 255, 255, 255, 255, 49, 0,
    0, 121, 247, 111, 109, 246, 126, 0,
    0, 208, 110, 0, 0, 105, 212, 1,
    88, 190, 2, 0, 0, 2, 187, 93,
    131, 12, 0, 0, 0, 0, 10, 130,
};

constexpr int ANTIGRAVITY_FEATURE_COUNT = 0;
static const FeatureLayer ANTIGRAVITY_FEATURES[1] = {
    {0, 0, 0, 0, nullptr, 0, 0, 0, false, false},
};

static const uint8_t KIRO[SIZE * SIZE] = {
    0, 0, 85, 219, 245, 172, 19, 0,
    0, 43, 252, 255, 255, 255, 182, 0,
    0, 128, 255, 251, 138, 141, 248, 27,
    0, 167, 255, 254, 191, 191, 253, 55,
    0, 219, 255, 255, 255, 255, 255, 43,
    58, 255, 255, 255, 255, 255, 241, 8,
    15, 113, 255, 255, 255, 255, 153, 0,
    0, 36, 229, 192, 197, 188, 17, 0,
};

constexpr int KIRO_FEATURE_COUNT = 0;
static const FeatureLayer KIRO_FEATURES[1] = {
    {0, 0, 0, 0, nullptr, 0, 0, 0, false, false},
};

static const uint8_t HERMES[SIZE * SIZE] = {
    0, 23, 148, 172, 172, 145, 3, 0,
    8, 155, 198, 168, 121, 193, 93, 0,
    75, 253, 240, 255, 243, 243, 208, 0,
    26, 175, 56, 68, 226, 241, 245, 11,
    0, 85, 25, 4, 247, 255, 251, 68,
    20, 168, 62, 53, 216, 255, 254, 110,
    107, 216, 255, 166, 207, 255, 245, 185,
    0, 95, 247, 147, 110, 38, 107, 67,
};

constexpr int HERMES_FEATURE_COUNT = 0;
static const FeatureLayer HERMES_FEATURES[1] = {
    {0, 0, 0, 0, nullptr, 0, 0, 0, false, false},
};

static const uint8_t ZAI[SIZE * SIZE] = {
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 12, 34, 34, 21, 34, 15, 0,
    0, 48, 136, 122, 223, 240, 31, 0,
    0, 0, 0, 163, 255, 89, 0, 0,
    0, 0, 83, 255, 163, 0, 0, 0,
    0, 28, 237, 226, 122, 136, 48, 0,
    0, 15, 34, 21, 34, 34, 12, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
};

constexpr int ZAI_FEATURE_COUNT = 0;
static const FeatureLayer ZAI_FEATURES[1] = {
    {0, 0, 0, 0, nullptr, 0, 0, 0, false, false},
};

}  // namespace OfficialDotGlyphs
