/* global window, document, location, localStorage */

(() => {
  'use strict';

  const data = window.AGENTDECK_DESIGN_SYSTEM;
  if (!data) throw new Error('Design-system manifest is missing.');

  const ui = {
    en: {
      preview: 'Preview',
      source: 'Markdown',
      metadata: 'Metadata',
      search: 'tokens, hardware, handover…',
      fallback: 'This page is not translated yet. Showing the canonical English source.',
      canonical: 'Canonical',
      translated: 'Reader translation',
      generated: 'Generated',
      tokens: 'Tokens',
      components: 'Components',
      assets: 'Assets',
      tokensDesc: 'Live values parsed from design/tokens.css, the cross-platform token source of truth.',
      componentsDesc: 'Reference specimens rendered with the same tokens used by this viewer.',
      assetsDesc: 'Every design resource the system actually uses, in one index: brand marks, generated device masks, creatures, icons, brand type, product marks, hardware photography, and the reference surfaces they came from.',
      tools: 'Specimens',
      catPreview: 'Library',
      catDesign: 'Design',
      catSpecs: 'Platforms',
      catEngineering: 'Project',
      docs: 'Documents',
      noResults: 'No catalog entries match this search.',
      componentsNote:
        'Every specimen below is real markup rendered by design/components.css and design/patterns.css — the same stylesheets the product surfaces load. Nothing here is a viewer-local imitation.',
      typeScale: 'Type scale',
      typeScaleNote:
        'Each row renders at the token’s true size. Kicker and mono-badge steps are set in JetBrains Mono when used.',
      specimenClass: 'Class',
      specSourceOnly: 'Source only',
      specOpen: 'View source on GitHub',
      livePreview: 'Live',
      openLivePreview: 'Open in Live Preview',
      assetGroups: {
        brand: 'Brand marks',
        masks: 'Generated dot-matrix masks',
        creatures: 'Creatures',
        icons: 'Icon set',
        typography: 'Brand type',
        product: 'Product marks & captures',
        photography: 'Hardware photography',
        reference: 'Reference surfaces',
      },
      assetGroupNotes: {
        brand: 'The product mark and the six agent marks, verbatim upstream. DESIGN.md R6 — never redraw them.',
        masks: 'Rendered from the brand SVGs by `pnpm generate-micro-glyphs`, parsed here straight out of the generated file. Device code may add color, shading, and motion around a mask, but must never replace it with hand-drawn agent geometry — regression tests pin each mark’s defining negative space.',
        creatures: 'Creatures are rendered live on the Live Preview surface, from the geometry SSOT. They are deliberately not redrawn here.',
        icons: 'The one canonical UI icon system. Never substitute a generic icon font.',
        typography: 'Two faces, no exceptions (DESIGN.md R3): IBM Plex Sans for text, JetBrains Mono for code and kickers. The CJK cut is the same family, so Korean and Japanese surfaces never fall back to a system font.',
        product: 'The AgentDeck mark itself, and the app capture that shows the tokens resolved in shipped UI. Distinct from the agent brand marks above.',
        photography: 'Hardware is photographed, never illustrated (DESIGN.md R7). Sources are committed; crops are generated by the crop table. When real photography is not ready, ship the diagonal-hatch placeholder instead of a drawing.',
        reference: 'Design provenance — superseded by this viewer wherever it covers the same ground. Kept because it records how the system got here.',
      },
    },
    ko: {
      preview: '미리보기',
      source: 'Markdown',
      metadata: '메타데이터',
      search: '토큰, 하드웨어, 인계 검색…',
      fallback: '아직 번역되지 않은 문서입니다. 영어 정본을 표시합니다.',
      canonical: '영어 정본',
      translated: '독자용 번역',
      generated: '생성',
      tokens: '토큰',
      components: '컴포넌트',
      assets: '에셋',
      tokensDesc: '크로스플랫폼 토큰 정본 design/tokens.css에서 읽은 실제 값입니다.',
      componentsDesc: '이 뷰어와 동일한 토큰으로 렌더한 기준 specimen입니다.',
      assetsDesc: '디자인 시스템이 실제로 쓰는 리소스를 한 곳에 모았어요 — 브랜드 마크, 생성된 기기 마스크, 크리처, 아이콘, 브랜드 서체, 제품 마크, 하드웨어 사진, 그리고 출처가 된 레퍼런스 표면까지.',
      tools: '미리보기',
      catPreview: '라이브러리',
      catDesign: '디자인',
      catSpecs: '플랫폼',
      catEngineering: '프로젝트',
      docs: '문서',
      noResults: '검색과 일치하는 문서가 없습니다.',
      componentsNote:
        '아래 specimen은 모두 design/components.css와 design/patterns.css가 그리는 실제 마크업이에요. 제품 화면이 쓰는 스타일시트와 같고, 뷰어용 모조 클래스는 없어요.',
      typeScale: '타입 스케일',
      typeScaleNote: '각 행은 토큰의 실제 크기로 렌더합니다. kicker와 mono-badge 단계는 실사용 시 JetBrains Mono예요.',
      specimenClass: '클래스',
      specSourceOnly: '소스 전용',
      specOpen: 'GitHub에서 소스 보기',
      livePreview: '라이브',
      openLivePreview: 'Live Preview에서 보기',
      assetGroups: {
        brand: '브랜드 마크',
        masks: '생성된 도트매트릭스 마스크',
        creatures: '크리처',
        icons: '아이콘 세트',
        typography: '브랜드 서체',
        product: '제품 마크와 캡처',
        photography: '하드웨어 사진',
        reference: '레퍼런스 표면',
      },
      assetGroupNotes: {
        brand: '제품 마크와 6개 에이전트 마크를 업스트림 그대로 씁니다. DESIGN.md R6 — 다시 그리지 않아요.',
        masks: '`pnpm generate-micro-glyphs`가 브랜드 SVG에서 만든 마스크를, 생성 파일에서 직접 파싱해 표시해요. 기기 코드는 마스크 주위에 색·음영·모션을 더할 수 있지만 손으로 그린 에이전트 도형으로 대체하면 안 됩니다 — 각 마크의 여백을 회귀 테스트가 고정하고 있어요.',
        creatures: '크리처는 지오메트리 SSOT를 통해 Live Preview에서 실제로 렌더됩니다. 여기서 다시 그리지 않아요.',
        icons: '정본 UI 아이콘 시스템 하나뿐이에요. 범용 아이콘 폰트로 대체 금지.',
        typography: '서체는 둘뿐입니다(DESIGN.md R3) — 본문은 IBM Plex Sans, 코드와 kicker는 JetBrains Mono. CJK도 같은 패밀리라서 한국어·일본어 화면이 시스템 폰트로 떨어지지 않아요.',
        product: 'AgentDeck 자체 마크와, 토큰이 실제 제품 UI에서 어떻게 해석되는지 보여주는 앱 캡처입니다. 위의 에이전트 브랜드 마크와는 구분돼요.',
        photography: '하드웨어는 사진으로 찍지, 그리지 않습니다(DESIGN.md R7). 원본은 커밋되어 있고 크롭은 크롭 테이블이 생성해요. 실사가 준비되지 않았다면 그림 대신 대각선 해치 플레이스홀더를 씁니다.',
        reference: '디자인 출처 기록 — 이 뷰어가 다루는 범위는 뷰어가 우선합니다. 여기까지 온 경로를 남기려고 보존해요.',
      },
    },
    ja: {
      preview: 'プレビュー',
      source: 'Markdown',
      metadata: 'メタデータ',
      search: 'token、hardware、handover…',
      fallback: 'この文書は未翻訳です。英語の正本を表示します。',
      canonical: '英語正本',
      translated: '読者向け翻訳',
      generated: '生成',
      tokens: 'トークン',
      components: 'コンポーネント',
      assets: 'アセット',
      tokensDesc: 'クロスプラットフォーム正本 design/tokens.css から取得した実値です。',
      componentsDesc: 'この Viewer と同じ token で描画する基準 specimen です。',
      assetsDesc: 'Design System が実際に使う resource を一つの index に集約 — brand mark、生成された device mask、クリーチャー、icon、ブランド書体、製品マーク、ハードウェア写真、そして出自となった reference 面まで。',
      tools: 'Specimen',
      catPreview: 'ライブラリ',
      catDesign: 'デザイン',
      catSpecs: 'プラットフォーム',
      catEngineering: 'プロジェクト',
      docs: '文書',
      noResults: '検索に一致する文書がありません。',
      componentsNote:
        '以下の specimen はすべて design/components.css と design/patterns.css が描く実際のマークアップです。製品面と同じ stylesheet を読み込み、Viewer 独自の模倣クラスはありません。',
      typeScale: 'タイプスケール',
      typeScaleNote: '各行は token の実サイズで描画します。kicker と mono-badge の段は実使用時 JetBrains Mono です。',
      specimenClass: 'クラス',
      specSourceOnly: 'ソースのみ',
      specOpen: 'GitHub でソースを見る',
      livePreview: 'ライブ',
      openLivePreview: 'Live Preview で開く',
      assetGroups: {
        brand: 'ブランドマーク',
        masks: '生成ドットマトリクス mask',
        creatures: 'クリーチャー',
        icons: 'アイコンセット',
        typography: 'ブランド書体',
        product: '製品マークとキャプチャ',
        photography: 'ハードウェア写真',
        reference: 'リファレンス面',
      },
      assetGroupNotes: {
        brand: '製品マークと 6 つの agent マークを upstream のまま使います。DESIGN.md R6 — 描き直しません。',
        masks: '`pnpm generate-micro-glyphs` が brand SVG から生成した mask を、生成ファイルから直接 parse して表示します。デバイス側は mask の周囲に色・陰影・motion を足せますが、手描きの agent 図形に置き換えてはいけません — 各マークの余白は regression test が固定しています。',
        creatures: 'クリーチャーは geometry SSOT を通じて Live Preview で実際に描画されます。ここでは描き直しません。',
        icons: '正本の UI アイコンシステムはこれ一つ。汎用アイコンフォントで代替しないこと。',
        typography: '書体は 2 つだけ（DESIGN.md R3）— 本文は IBM Plex Sans、コードと kicker は JetBrains Mono。CJK も同じファミリーなので、日本語・韓国語の面が system font に落ちません。',
        product: 'AgentDeck 自体のマークと、token が実際の製品 UI でどう解決されるかを示すアプリキャプチャです。上の agent ブランドマークとは区別します。',
        photography: 'ハードウェアは撮影するもので、描くものではありません（DESIGN.md R7）。元写真は commit 済み、crop は crop table が生成します。実写が未整備なら、描かずに斜めハッチの placeholder を出します。',
        reference: 'デザインの出自記録 — この Viewer が扱う範囲は Viewer が優先します。経緯を残すために保存しています。',
      },
    },
  };

  const special = new Set(['tokens', 'components', 'assets']);
  const knownPaths = new Map();
  for (const document of data.documents) {
    for (const locale of Object.values(document.locales)) knownPaths.set(locale.path, document.id);
  }

  const els = {
    navigation: document.querySelector('#navigation'),
    search: document.querySelector('#search'),
    locale: document.querySelector('#lang'),
    generatedAt: document.querySelector('#generated-at'),
    fallback: document.querySelector('#fallback'),
    eyebrow: document.querySelector('#eyebrow'),
    title: document.querySelector('#title'),
    description: document.querySelector('#description'),
    badges: document.querySelector('#badges'),
    tabs: document.querySelector('.view-tabs'),
    tabButtons: [...document.querySelectorAll('.view-tabs button')],
    view: document.querySelector('#view'),
  };

  let locale = localStorage.getItem('agentdeck-design-locale') || data.defaultLocale;
  if (!data.locales.includes(locale)) locale = data.defaultLocale;
  let activeId = decodeURIComponent(location.hash.slice(1)) || 'tokens';
  if (!special.has(activeId) && !data.documents.some((item) => item.id === activeId)) activeId = 'tokens';
  let viewMode = 'preview';
  let query = '';

  function escapeHtml(value) {
    return String(value).replace(
      /[&<>"']/g,
      (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character],
    );
  }

  function inlineMarkdown(value, sourcePath) {
    const code = [];
    // Extract inline code first to avoid mangling
    let output = String(value).replace(/`([^`]+)`/g, (_, inner) => {
      code.push(`<code>${escapeHtml(inner)}</code>`);
      return `\u0000CODE${code.length - 1}\u0000`;
    });
    // Extract images before escaping (![alt](url))
    const images = [];
    output = output.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, (_, alt, src) => {
      const resolvedSrc = /^https?:/.test(src) ? src : src;
      images.push(`<img class="md-img" src="${escapeHtml(resolvedSrc)}" alt="${escapeHtml(alt)}" data-lightbox data-caption="${escapeHtml(alt)}">`);
      return `\u0000IMG${images.length - 1}\u0000`;
    });
    output = escapeHtml(output)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/_([^_]+)_/g, '<em>$1</em>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, label, href) => {
        const target = resolveLink(href, sourcePath);
        return `<a href="${escapeHtml(target)}">${label}</a>`;
      });
    output = output.replace(/\u0000CODE(\d+)\u0000/g, (_, index) => code[Number(index)]);
    output = output.replace(/\u0000IMG(\d+)\u0000/g, (_, index) => images[Number(index)]);
    return output;
  }

  function resolveLink(href, sourcePath) {
    if (/^(https?:|mailto:|#)/.test(href)) return href;
    const base = sourcePath.includes('/') ? sourcePath.slice(0, sourcePath.lastIndexOf('/') + 1) : '';
    const normalized = normalizePath(`${base}${href}`);
    const documentId = knownPaths.get(normalized);
    if (documentId) return `#${encodeURIComponent(documentId)}`;
    return `https://github.com/puritysb/AgentDeck/blob/master/${normalized}`;
  }

  function normalizePath(value) {
    const stack = [];
    for (const part of value.split('/')) {
      if (!part || part === '.') continue;
      if (part === '..') stack.pop();
      else stack.push(part);
    }
    return stack.join('/');
  }

  function isTableSeparator(line) {
    return /^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$/.test(line);
  }

  function cells(line) {
    return line
      .trim()
      .replace(/^\|/, '')
      .replace(/\|$/, '')
      .split('|')
      .map((cell) => cell.trim());
  }

  function markdownToHtml(markdown, sourcePath) {
    const lines = markdown.replace(/\r\n/g, '\n').split('\n');
    const html = [];
    let index = 0;
    while (index < lines.length) {
      const line = lines[index];
      if (!line.trim()) {
        index += 1;
        continue;
      }
      if (/^```/.test(line)) {
        const language = line.slice(3).trim();
        const code = [];
        index += 1;
        while (index < lines.length && !/^```/.test(lines[index])) code.push(lines[index++]);
        index += 1;
        html.push(`<pre><code data-language="${escapeHtml(language)}">${escapeHtml(code.join('\n'))}</code></pre>`);
        continue;
      }
      if (index + 1 < lines.length && line.includes('|') && isTableSeparator(lines[index + 1])) {
        const headers = cells(line);
        index += 2;
        const rows = [];
        while (index < lines.length && lines[index].includes('|') && lines[index].trim())
          rows.push(cells(lines[index++]));
        html.push(
          `<div class="table-wrap"><table><thead><tr>${headers.map((cell) => `<th>${inlineMarkdown(cell, sourcePath)}</th>`).join('')}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${inlineMarkdown(cell, sourcePath)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`,
        );
        continue;
      }
      const heading = line.match(/^(#{1,6})\s+(.+)$/);
      if (heading) {
        const level = heading[1].length;
        html.push(`<h${level}>${inlineMarkdown(heading[2], sourcePath)}</h${level}>`);
        index += 1;
        continue;
      }
      if (/^\s*[-*]\s+/.test(line) || /^\s*\d+\.\s+/.test(line)) {
        const ordered = /^\s*\d+\./.test(line);
        const tag = ordered ? 'ol' : 'ul';
        const items = [];
        const pattern = ordered ? /^\s*\d+\.\s+(.+)$/ : /^\s*[-*]\s+(.+)$/;
        while (index < lines.length) {
          const match = lines[index].match(pattern);
          if (!match) break;
          items.push(`<li>${inlineMarkdown(match[1], sourcePath)}</li>`);
          index += 1;
        }
        html.push(`<${tag}>${items.join('')}</${tag}>`);
        continue;
      }
      if (/^>\s?/.test(line)) {
        const quote = [];
        while (index < lines.length && /^>\s?/.test(lines[index])) quote.push(lines[index++].replace(/^>\s?/, ''));
        html.push(`<blockquote>${inlineMarkdown(quote.join(' '), sourcePath)}</blockquote>`);
        continue;
      }
      if (/^---+$/.test(line.trim())) {
        html.push('<hr>');
        index += 1;
        continue;
      }
      const paragraph = [line.trim()];
      index += 1;
      while (
        index < lines.length &&
        lines[index].trim() &&
        !/^(#{1,6})\s|^```|^>\s?|^\s*[-*]\s+|^\s*\d+\.\s+|^---+$/.test(lines[index])
      ) {
        if (index + 1 < lines.length && lines[index].includes('|') && isTableSeparator(lines[index + 1])) break;
        paragraph.push(lines[index].trim());
        index += 1;
      }
      html.push(`<p>${inlineMarkdown(paragraph.join(' '), sourcePath)}</p>`);
    }
    return html.join('');
  }

  function localizedDocument(documentEntry) {
    return {
      page: documentEntry.locales[locale] || documentEntry.locales.en,
      fallback: !documentEntry.locales[locale],
    };
  }

  function strings() {
    return ui[locale];
  }

  function updateChrome() {
    const text = strings();
    els.locale.value = locale;
    els.search.placeholder = text.search;
    els.tabButtons[0].textContent = text.preview;
    els.tabButtons[1].textContent = text.source;
    els.tabButtons[2].textContent = text.metadata;
    document.documentElement.lang = locale === 'ko' ? 'ko' : locale === 'ja' ? 'ja' : 'en';
    const date = new Date(data.generatedAt);
    els.generatedAt.textContent = `${text.generated} ${date.toLocaleDateString(document.documentElement.lang)}`;
  }

  // Fixed category display order — determines rail section sequence.
  const CATEGORY_ORDER = ['Preview', 'Design', 'Specs', 'Engineering'];

  // Project section collapses by default; the new key resets the formerly
  // over-expanded Engineering rail for returning visitors.
  const PROJECT_KEY = 'agentdeck-design-project-open';
  let projectOpen = localStorage.getItem(PROJECT_KEY) === 'true';

  function categoryLabel(raw) {
    const t = strings();
    if (raw === 'Preview') return t.catPreview;
    if (raw === 'Design') return t.catDesign;
    if (raw === 'Specs') return t.catSpecs;
    if (raw === 'Engineering') return t.catEngineering;
    return raw;
  }

  function navigationItems() {
    const items = data.documents.map((entry) => {
      const localized = localizedDocument(entry);
      const title = localized.page.metadata.title;
      const label = data.navigationLabels[entry.id][locale];
      return {
        id: entry.id,
        title,
        label,
        category: localized.page.metadata.category,
        locale: localized.page.metadata.locale,
        search:
          `${label} ${title} ${localized.page.metadata.description} ${localized.page.body}`.toLowerCase(),
      };
    });
    items.push(
      {
        id: 'tokens',
        title: strings().tokens,
        label: strings().tokens,
        category: 'Preview',
        locale: 'live',
        search: 'tokens colors type spacing radius motion preview live',
      },
      {
        id: 'components',
        title: strings().components,
        label: strings().components,
        category: 'Preview',
        locale: 'live',
        search: 'components buttons badges status placeholder typography preview live',
      },
      {
        id: 'assets',
        title: strings().assets,
        label: strings().assets,
        category: 'Preview',
        locale: 'live',
        search: 'assets logo icon brands masks glyphs creatures reference mockups typography fonts plex jetbrains photography hardware photos captures claude codex openclaw opencode antigravity kiro preview live',
      },
    );
    return items.filter((item) => !query || item.search.includes(query));
  }

  function renderNavigation() {
    const grouped = new Map();
    // Collect items in fixed order
    const allItems = navigationItems();
    const orderedKeys = [];
    for (const item of allItems) {
      if (!grouped.has(item.category)) {
        grouped.set(item.category, []);
        orderedKeys.push(item.category);
      }
      grouped.get(item.category).push(item);
    }

    if (grouped.size === 0) {
      els.navigation.innerHTML = `<p class="description">${escapeHtml(strings().noResults)}</p>`;
      return;
    }

    // Sort keys by CATEGORY_ORDER, unknown categories go last
    orderedKeys.sort((a, b) => {
      const ai = CATEGORY_ORDER.indexOf(a);
      const bi = CATEGORY_ORDER.indexOf(b);
      if (ai === -1 && bi === -1) return 0;
      if (ai === -1) return 1;
      if (bi === -1) return -1;
      return ai - bi;
    });

    // Open Project only when it owns the active document.
    const projectItems = grouped.get('Engineering') || [];
    const activeInProject = projectItems.some((item) => item.id === activeId);
    if (activeInProject) projectOpen = true;

    // Searching spans every document, so reveal Project matches while filtering.
    const searching = query.length > 0;

    els.navigation.innerHTML = orderedKeys
      .map((category) => {
        const items = grouped.get(category);
        const isProject = category === 'Engineering';
        const isOpen = !isProject || projectOpen || searching;
        const label = categoryLabel(category);
        const itemCount = items.length;
        if (isProject) {
          return `<section class="rail-group rail-group--collapsible${isOpen ? ' is-open' : ''}" data-category="Engineering">
            <button class="rail-title rail-title--toggle" aria-expanded="${isOpen}" data-toggle="Engineering">
              <span>${escapeHtml(label)}</span>
              <span class="rail-toggle-count">${itemCount}</span>
              <span class="rail-toggle-chevron" aria-hidden="true"></span>
            </button>
            <div class="rail-group-body">
              <div class="rail-group-inner">
                ${items.map((item) => `<button class="rail-button${item.id === activeId ? ' active' : ''}" data-id="${escapeHtml(item.id)}" title="${escapeHtml(item.title)}"><span>${escapeHtml(item.label)}</span></button>`).join('')}
              </div>
            </div>
          </section>`;
        }
        return `<section class="rail-group">
          <h3 class="rail-title">${escapeHtml(label)}</h3>
          ${items.map((item) => `<button class="rail-button${item.id === activeId ? ' active' : ''}" data-id="${escapeHtml(item.id)}" title="${escapeHtml(item.title)}"><span>${escapeHtml(item.label)}</span></button>`).join('')}
        </section>`;
      })
      .join('');

    for (const button of els.navigation.querySelectorAll('[data-id]')) {
      button.addEventListener('click', () => activate(button.dataset.id));
    }
    // Collapsible Project toggle (canonical category remains Engineering).
    const toggle = els.navigation.querySelector('[data-toggle="Engineering"]');
    if (toggle) {
      toggle.addEventListener('click', () => {
        projectOpen = !projectOpen;
        localStorage.setItem(PROJECT_KEY, String(projectOpen));
        renderNavigation();
      });
    }
  }

  function badge(label, className = '') {
    return `<span class="badge ${className}">${escapeHtml(label)}</span>`;
  }

  function renderDocument() {
    const entry = data.documents.find((item) => item.id === activeId);
    const localized = localizedDocument(entry);
    const page = localized.page;
    const meta = page.metadata;
    els.tabs.hidden = false;
    els.fallback.hidden = !localized.fallback;
    els.fallback.textContent = localized.fallback ? strings().fallback : '';
    els.eyebrow.textContent = `${meta.category} · ${page.path}`;
    els.title.textContent = meta.title;
    els.description.textContent = meta.description;
    els.badges.innerHTML =
      badge(meta.canonical ? strings().canonical : strings().translated, meta.canonical ? 'canonical' : '') +
      badge(meta.status, meta.status === 'required' ? 'required' : '') +
      badge(meta.locale);

    if (viewMode === 'preview') {
      // The page header already renders the document title (frontmatter), so a
      // leading body H1 would repeat it at display size — drop it in preview.
      // Markdown/source tabs keep the raw file untouched.
      const body = page.body.replace(/^\s*#\s+[^\n]+\n/, '');
      els.view.innerHTML = `<article class="markdown">${markdownToHtml(body, page.path)}</article>`;
    } else if (viewMode === 'source') {
      els.view.innerHTML = `<pre class="source-code">${escapeHtml(page.raw)}</pre>`;
    } else {
      els.view.innerHTML = metadataView(meta, page.path);
    }
  }

  function metadataView(metadata, sourcePath) {
    const rows = { ...metadata, path: sourcePath };
    return `<dl class="metadata-grid">${Object.entries(rows)
      .map(
        ([key, value]) =>
          `<div><dt>${escapeHtml(key)}</dt><dd>${Array.isArray(value) ? `<ul>${value.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul>` : escapeHtml(value)}</dd></div>`,
      )
      .join('')}</dl>`;
  }

  const COLOR_GROUPS = new Set(['Tide', 'Ink', 'Kelp', 'Coral', 'Amber', 'Brand', 'Status', 'Product UI']);

  /* A token is only understood by looking at what it does. Each group gets a
   * specimen that exercises the value the way a consumer would apply it. */
  function tokenSpecimen(token) {
    const value = escapeHtml(token.value);
    if (COLOR_GROUPS.has(token.group)) return `<div class="tk-stage swatch" style="--swatch:${value}"></div>`;
    if (token.group === 'Radius') {
      return `<div class="tk-stage"><div class="tk-radius" style="border-radius:${value}"></div></div>`;
    }
    if (token.group === 'Layout') {
      return `<div class="tk-stage tk-stage--bar"><div class="tk-bar" style="width:min(${value}, 100%)"></div></div>`;
    }
    if (token.group === 'Type') {
      const property = token.name.startsWith('--font-')
        ? `font-family:${value}`
        : token.name.startsWith('--tr-')
          ? `letter-spacing:${value}`
          : `font-size:min(${value}, 30px)`;
      return `<div class="tk-stage"><span class="tk-type" style="${property}">Ag한글</span></div>`;
    }
    if (token.group === 'Motion') {
      const animation = token.name.startsWith('--ease-')
        ? `animation-duration:800ms;animation-timing-function:${value}`
        : `animation-duration:${value};animation-timing-function:var(--ease-snap)`;
      return `<div class="tk-stage tk-stage--motion"><span class="tk-motion" style="${animation}"></span></div>`;
    }
    if (token.group === 'Shadow') {
      return `<div class="tk-stage tk-stage--shadow"><div class="tk-shadow" style="box-shadow:${value}"></div></div>`;
    }
    return `<div class="tk-stage swatch" style="--swatch:${value}"></div>`;
  }

  function renderTokens() {
    const grouped = new Map();
    for (const token of data.tokens) {
      if (!grouped.has(token.group)) grouped.set(token.group, []);
      grouped.get(token.group).push(token);
    }
    const sections = [...grouped.entries()]
      .map(
        ([group, tokens]) =>
          `<section class="token-section"><h3>${escapeHtml(group)}</h3><div class="token-grid">${tokens.map((token) => `<article class="token-card">${tokenSpecimen(token)}<div class="token-copy"><strong>${escapeHtml(token.name)}</strong><small>${escapeHtml(token.value)}</small></div></article>`).join('')}</div></section>`,
      )
      .join('');
    specialHeader(
      strings().tokens,
      strings().tokensDesc,
      'Foundations · design/tokens.css',
      badge('CSS SSOT', 'canonical'),
    );
    // specialHeader already prints the description — repeating it here read as a
    // rendering bug once the copy grew past one line.
    els.view.innerHTML = `<div class="token-groups">${sections}</div>`;
  }

  function renderAssets() {
    const text = strings();
    specialHeader(
      text.assets,
      text.assetsDesc,
      'Foundations · design resources index',
      badge(`${data.assets.total} assets`, 'canonical'),
    );
    const sections = data.assets.groups
      .map(
        (group) =>
          `<section class="asset-section"><header class="asset-section-head"><h3>${escapeHtml(text.assetGroups[group.id] || group.id)}</h3><p>${escapeHtml(text.assetGroupNotes[group.id] || '')}</p></header><div class="asset-grid">${group.items.map(assetCard).join('')}</div></section>`,
      )
      .join('');
    els.view.innerHTML = `<div class="asset-groups">${sections}</div>`;
  }

  function assetMeta(asset) {
    const parts = [asset.source];
    if (asset.type) parts.push(asset.type);
    if (asset.bytes) parts.push(`${asset.bytes.toLocaleString()} B`);
    return `<p>${parts.map(escapeHtml).join(' · ')}</p>`;
  }

  function assetCard(asset) {
    if (asset.kind === 'mask') {
      /* `asset.svg` is emitted by the builder from the generated mask file, not
       * from user input — injected as markup so the real pixels render. */
      return `<article class="asset-card asset-card--mask"><div class="asset-stage asset-stage--mask">${asset.svg}</div><h3>${escapeHtml(asset.name)}</h3><p class="asset-note">${escapeHtml(asset.surface)} · ${asset.lit} lit cells</p>${assetMeta(asset)}</article>`;
    }
    if (asset.kind === 'type') {
      /* Set in the shipped face itself — a font card that renders in a fallback
       * would be showing the reader the wrong thing. */
      const family = `${asset.family}, ${asset.family === 'JetBrains Mono' ? 'monospace' : 'sans-serif'}`;
      return `<article class="asset-card asset-card--type"><div class="asset-stage asset-stage--type" style="font-family:${escapeHtml(family)}"><span class="face-aa">Ag</span><span class="face-sample">${escapeHtml(asset.sample)}</span></div><h3>${escapeHtml(asset.name)}</h3><p class="asset-note">${escapeHtml(asset.role)} · ${escapeHtml(asset.note)}</p>${assetMeta(asset)}<a class="asset-link" href="${escapeHtml(asset.url)}" rel="noreferrer">${escapeHtml(strings().specOpen)}</a></article>`;
    }
    if (asset.kind === 'link') {
      return `<article class="asset-card asset-card--link"><div class="asset-stage asset-stage--spec"><div class="ad-hatch asset-hatch"><span class="ad-tier ad-tier--store">${escapeHtml(strings().livePreview)}</span></div></div><h3>${escapeHtml(asset.name)}</h3><p class="asset-note">${escapeHtml(asset.note || '')}</p><a class="asset-link" href="${escapeHtml(asset.url)}">${escapeHtml(strings().openLivePreview)}</a></article>`;
    }
    if (asset.kind === 'spec') {
      // Source-only pointer: the viewer must not try to render JSX or HTML here.
      return `<article class="asset-card asset-card--spec"><div class="asset-stage asset-stage--spec"><div class="ad-hatch asset-hatch"><span class="ad-tier ad-tier--cli">${escapeHtml(strings().specSourceOnly)}</span></div></div><h3>${escapeHtml(asset.name)}</h3><p class="asset-note">${escapeHtml(asset.note || '')}</p>${assetMeta(asset)}<a class="asset-link" href="${escapeHtml(asset.url)}" rel="noreferrer">${escapeHtml(strings().specOpen)}</a></article>`;
    }
    // Default image card — clickable for lightbox
    return `<article class="asset-card asset-card--img" tabindex="0" role="button" aria-label="View ${escapeHtml(asset.name)}" data-lightbox-src="${escapeHtml(asset.url)}" data-lightbox-cap="${escapeHtml(asset.name)}">
      <div class="asset-stage">
        <img src="${escapeHtml(asset.url)}" alt="${escapeHtml(asset.name)}" loading="lazy">
        <span class="asset-zoom-hint" aria-hidden="true">&#x2B07; Click to zoom</span>
      </div>
      <h3>${escapeHtml(asset.name)}</h3>
      ${assetMeta(asset)}
    </article>`;
  }

  /* Declarative specimen list. Every `html` string is canonical `.ad-*` markup
   * from design/components.css + design/patterns.css — never a viewer-local
   * imitation, so a rule change in the design system shows up here immediately.
   */
  const COMPONENT_SPECIMENS = [
    {
      group: 'Actions',
      title: 'Buttons',
      classes: '.ad-btn--primary · --ghost · --coral',
      note: 'DESIGN.md §5.1. Primary is an ink fill that lifts 1px on hover; ghost inverts; coral marks the developer edge. Primary may carry a kelp mono badge.',
      html: `<button class="ad-btn ad-btn--primary" type="button">Get on App Store<span class="ad-btn-badge">App Store</span></button>
        <button class="ad-btn ad-btn--ghost" type="button">Read spec</button>
        <button class="ad-btn ad-btn--coral" type="button">Run npx setup</button>`,
    },
    {
      group: 'Editorial',
      title: 'Kicker',
      classes: '.ad-kicker · --coral · --kelp-light',
      note: 'DESIGN.md §5.3. Mono, 12px, 0.18em tracked, uppercase. Kelp on light, coral in developer sections, kelp-300 on ink.',
      html: `<span class="ad-kicker">Foundations</span>
        <span class="ad-kicker ad-kicker--coral">Developer</span>
        <span class="ad-surface-ink specimen-inkpad"><span class="ad-kicker ad-kicker--kelp-light">On ink</span></span>`,
    },
    {
      group: 'Tiers',
      title: 'Tier badges',
      classes: '.ad-tier--store · --store-on-dark · --dev · --cli',
      note: 'DESIGN.md §5.2. Store reads ink-on-sand, or kelp-on-ink when the surface is dark. Developer is always a solid coral fill; CLI is the one outlined variant.',
      html: `<span class="ad-tier ad-tier--store">App Store</span>
        <span class="ad-surface-ink specimen-inkpad"><span class="ad-tier ad-tier--store-on-dark">App Store</span></span>
        <span class="ad-tier ad-tier--dev">Developer</span>
        <span class="ad-tier ad-tier--cli">CLI</span>`,
    },
    {
      group: 'Chrome',
      title: 'Hero kicker chip',
      classes: '.ad-chip',
      note: 'DESIGN.md §5.4. Pill on tide-100 with a leading kelp dot and a 4px ring at 18% alpha.',
      html: `<span class="ad-chip">20 surfaces · one daemon</span>`,
    },
    {
      group: 'Signal',
      title: 'Status dots — all four states',
      classes: '.ad-dot--idle · --processing · --awaiting · --error',
      note: 'DESIGN.md §2.7 + R4. Only the amber awaiting dot animates (1.1s ease-in-out). Kelp and coral must stay perfectly still — motion is how the user knows they are being asked for something.',
      wide: true,
      html: `<span class="ad-status"><span class="ad-dot ad-dot--idle"></span>Idle</span>
        <span class="ad-status"><span class="ad-dot ad-dot--processing"></span>Processing</span>
        <span class="ad-status"><span class="ad-dot ad-dot--awaiting"></span>Awaiting input</span>
        <span class="ad-status"><span class="ad-dot ad-dot--error"></span>Error</span>`,
    },
    {
      group: 'Containers',
      title: 'Cards',
      classes: '.ad-card · --ink · --dev',
      note: 'The neutral card, the ink card for dark sections, and the developer card with its 3px coral left rule.',
      wide: true,
      html: `<div class="specimen-cards">
          <div class="ad-card"><strong>Default</strong><p class="specimen-copy">Sand fill, hairline ink border, 14px radius.</p></div>
          <div class="ad-surface-ink specimen-inkwrap"><div class="ad-card ad-card--ink"><strong>Ink</strong><p class="specimen-copy">Translucent white over an ink section.</p></div></div>
          <div class="ad-card ad-card--dev"><strong>Developer</strong><p class="specimen-copy">Coral left rule, 12px radius.</p></div>
        </div>`,
    },
    {
      group: 'Chrome',
      title: 'Language switcher',
      classes: '.ad-lang',
      note: 'DESIGN.md §1.5. KO/EN/JA are peers on the same pill; the active locale takes the ink fill.',
      html: `<div class="ad-lang">
          <button type="button" aria-pressed="true">EN</button>
          <button type="button" aria-pressed="false">한국어</button>
          <button type="button" aria-pressed="false">日本語</button>
        </div>`,
    },
    {
      group: 'Hardware',
      title: 'Device tile',
      classes: '.ad-device',
      note: 'DESIGN.md §5.8. Tier badge top-left, device name pinned to the bottom in 13px sans 500, 96px min-height.',
      html: `<div class="specimen-devices">
          <div class="ad-device"><span class="ad-tier ad-tier--store">App Store</span><span class="ad-device-name">macOS menubar</span></div>
          <div class="ad-device"><span class="ad-tier ad-tier--dev">Dev</span><span class="ad-device-name">InkDeck 7.5" e-ink</span></div>
          <div class="ad-device"><span class="ad-tier ad-tier--dev">Dev</span><span class="ad-device-name">TC001 LED 32×8</span></div>
        </div>`,
    },
    {
      group: 'Machine',
      title: 'Code block',
      classes: '.ad-code',
      note: 'DESIGN.md §5.7. Mono on ink with a leading kelp-300 `$` supplied by the pseudo-element — never typed into the copy.',
      html: `<span class="ad-code">npx @agentdeck/setup</span>`,
    },
    {
      group: 'Signal',
      title: 'Inline notices',
      classes: '.ad-notice--awaiting · --error · --ok',
      note: 'Tinted at 8% over the hairline border. Notices carry status color but never animate — the dot does that job.',
      wide: true,
      html: `<div class="specimen-stack">
          <div class="ad-notice ad-notice--awaiting"><span class="ad-dot ad-dot--awaiting"></span>Claude Code is waiting on a permission decision.</div>
          <div class="ad-notice ad-notice--error"><span class="ad-dot ad-dot--error"></span>Board <code>ips10</code> dropped its WiFi socket.</div>
          <div class="ad-notice ad-notice--ok"><span class="ad-dot ad-dot--processing"></span>OTA verified — buildHash matches.</div>
        </div>`,
    },
    {
      group: 'Patterns',
      title: 'Hatch and honest placeholder',
      classes: '.ad-hatch · .ad-placeholder',
      note: 'DESIGN.md §5.10 + R7. When a real hardware photo is not ready we ship the diagonal hatch with a mono caption — we never illustrate hardware with a hand-drawn SVG.',
      wide: true,
      html: `<div class="specimen-patterns">
          <div class="ad-hatch specimen-hatch"></div>
          <div class="ad-placeholder" data-label="// menubar popup — sessions list"></div>
        </div>`,
    },
    {
      group: 'Patterns',
      title: 'Surface paints',
      classes: '.ad-surface-sand · --cream · --ink',
      note: 'The three section grounds. Sand is the default page, cream separates a band, ink carries the dark editorial sections.',
      wide: true,
      html: `<div class="specimen-surfaces">
          <div class="ad-surface-sand specimen-surface"><span class="ad-kicker">Sand</span><small>--tide-50</small></div>
          <div class="ad-surface-cream specimen-surface"><span class="ad-kicker">Cream</span><small>--tide-100</small></div>
          <div class="ad-surface-ink specimen-surface"><span class="ad-kicker ad-kicker--kelp-light">Ink</span><small>--ink-900</small></div>
        </div>`,
    },
  ];

  function typeScaleSpecimen() {
    const steps = data.tokens.filter((token) => token.name.startsWith('--t-'));
    const rows = steps
      .map(
        (token) =>
          `<div class="type-row"><code>${escapeHtml(token.name)}</code><small>${escapeHtml(token.value)}</small><span class="type-sample" style="font-size:${escapeHtml(token.value)}">Ag 한글 カナ</span></div>`,
      )
      .join('');
    return {
      group: 'Typography',
      title: `${strings().typeScale} — ${steps.length} steps`,
      classes: '--t-hero … --t-mono-badge',
      note: strings().typeScaleNote,
      wide: true,
      html: `<div class="type-scale">${rows}</div>`,
    };
  }

  function specimenCard(spec) {
    const copyId = `copy-${Math.random().toString(36).slice(2)}`;
    return `<article class="specimen${spec.wide ? ' specimen--wide' : ''}">
      <header class="specimen-head">
        <span class="ad-kicker">${escapeHtml(spec.group)}</span>
        <h3>${escapeHtml(spec.title)}</h3>
        <div class="specimen-head-row">
          <code class="specimen-class"><span class="specimen-class-label">${escapeHtml(strings().specimenClass)}</span>${escapeHtml(spec.classes)}</code>
          <button class="specimen-copy-btn" data-copy-id="${copyId}" title="Copy HTML" aria-label="Copy HTML for ${escapeHtml(spec.title)}">&#x2398; Copy</button>
        </div>
      </header>
      <div class="specimen-stage" id="${copyId}">${spec.html}</div>
      <p class="specimen-note">${escapeHtml(spec.note)}</p>
    </article>`;
  }

  function renderComponents() {
    specialHeader(
      strings().components,
      strings().componentsDesc,
      'Foundations · design/components.css + design/patterns.css',
      badge('Canonical CSS', 'canonical'),
    );
    const specimens = [...COMPONENT_SPECIMENS, typeScaleSpecimen()];
    els.view.innerHTML = `<p class="specimen-intro">${escapeHtml(strings().componentsNote)}</p><div class="specimen-grid">${specimens.map(specimenCard).join('')}</div>`;
  }

  function specialHeader(title, description, eyebrow, badges) {
    els.tabs.hidden = true;
    els.fallback.hidden = true;
    els.eyebrow.textContent = eyebrow;
    els.title.textContent = title;
    els.description.textContent = description;
    els.badges.innerHTML = badges;
  }

  function render() {
    updateChrome();
    renderNavigation();
    if (activeId === 'tokens') renderTokens();
    else if (activeId === 'components') renderComponents();
    else if (activeId === 'assets') renderAssets();
    else renderDocument();
  }

  function activate(id) {
    activeId = id;
    viewMode = 'preview';
    location.hash = encodeURIComponent(id);
    updateTabs();
    render();
    document.querySelector('#content').focus({ preventScroll: true });
  }

  function updateTabs() {
    for (const button of els.tabButtons) {
      const active = button.dataset.view === viewMode;
      button.classList.toggle('active', active);
      button.setAttribute('aria-selected', String(active));
    }
  }

  els.search.addEventListener('input', () => {
    query = els.search.value.trim().toLowerCase();
    renderNavigation();
  });
  els.locale.addEventListener('change', () => {
    locale = els.locale.value;
    localStorage.setItem('agentdeck-design-locale', locale);
    render();
  });
  for (const button of els.tabButtons) {
    button.addEventListener('click', () => {
      viewMode = button.dataset.view;
      updateTabs();
      renderDocument();
    });
  }
  window.addEventListener('hashchange', () => {
    const next = decodeURIComponent(location.hash.slice(1));
    if (next && next !== activeId && (special.has(next) || data.documents.some((item) => item.id === next))) {
      activeId = next;
      viewMode = 'preview';
      updateTabs();
      render();
    }
  });

  // ── Lightbox ─────────────────────────────────────────────────────────────
  const lightbox = document.getElementById('lightbox');
  const lightboxImg = document.getElementById('lightbox-img');
  const lightboxCap = document.getElementById('lightbox-cap');

  function openLightbox(src, caption) {
    lightboxImg.src = src;
    lightboxImg.alt = caption || '';
    lightboxCap.textContent = caption || '';
    lightbox.hidden = false;
    document.body.classList.add('lightbox-open');
    lightbox.querySelector('.lightbox-close').focus();
  }

  function closeLightbox() {
    lightbox.hidden = true;
    document.body.classList.remove('lightbox-open');
  }

  lightbox.querySelector('.lightbox-close').addEventListener('click', closeLightbox);
  lightbox.addEventListener('click', (e) => { if (e.target === lightbox) closeLightbox(); });
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && !lightbox.hidden) closeLightbox(); });

  // Delegate: asset cards (data-lightbox-src) + markdown images (data-lightbox)
  document.addEventListener('click', (e) => {
    const card = e.target.closest('[data-lightbox-src]');
    if (card) { openLightbox(card.dataset.lightboxSrc, card.dataset.lightboxCap); return; }
    const img = e.target.closest('img[data-lightbox]');
    if (img) { openLightbox(img.src, img.dataset.caption || img.alt); return; }
  });
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' || e.key === ' ') {
      const card = e.target.closest('[data-lightbox-src]');
      if (card) { e.preventDefault(); openLightbox(card.dataset.lightboxSrc, card.dataset.lightboxCap); }
    }
  });

  // ── Copy HTML toast ───────────────────────────────────────────────────────
  const copyToast = document.getElementById('copy-toast');
  let toastTimer;

  function showToast() {
    copyToast.hidden = false;
    copyToast.classList.add('is-visible');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => {
      copyToast.classList.remove('is-visible');
      setTimeout(() => { copyToast.hidden = true; }, 300);
    }, 1800);
  }

  document.addEventListener('click', (e) => {
    const btn = e.target.closest('.specimen-copy-btn');
    if (!btn) return;
    const stage = document.getElementById(btn.dataset.copyId);
    if (!stage) return;
    const html = stage.innerHTML.trim();
    navigator.clipboard.writeText(html).then(showToast).catch(() => {
      // Fallback for non-secure contexts
      const ta = document.createElement('textarea');
      ta.value = html; ta.style.position = 'fixed'; ta.style.opacity = '0';
      document.body.appendChild(ta); ta.select();
      document.execCommand('copy'); document.body.removeChild(ta);
      showToast();
    });
  });

  updateTabs();
  render();
})();
