// GENERATED by scripts/generate-mlx-safety.mjs. Do not edit.
// Policy source: shared/src/mlx-safety.ts; cross-runtime vectors in shared/mlx-safety-vectors.json.
import Foundation

#if os(macOS)
enum MlxSafetyRules {
    static let cooldown: TimeInterval = 300
    static let probeTimeout: TimeInterval = 2
    static let maxEndpoints = 64
    static func pin(_ value: String?) -> String? {
        guard let value = value?.trimmingCharacters(in: .whitespacesAndNewlines),
              !["", "default", "qwen3-30b"].contains(value) else { return nil }
        return value
    }
    static func select(loadedKnown: Bool, loaded: String?, catalog: [String], requested: String?) throws -> String {
        let models = Set(catalog.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty })
        let model = loadedKnown ? pin(loaded) : (models.count == 1 ? models.first : nil)
        guard let model, !model.lowercased().contains("nanollava") else {
            throw MlxSafetyError.refused("MLX has no unambiguous resident chat model")
        }
        if let requested = pin(requested), requested != model {
            throw MlxSafetyError.refused("MLX model mismatch; refusing model replacement")
        }
        return model
    }
    static func metricsProblem(_ metrics: [String: Any]) -> String? {
        let summary = metrics["summary"] as? [String: Any] ?? [:]
        let server = metrics["server"] as? [String: Any] ?? [:]
        if (summary["in_flight"] as? NSNumber)?.doubleValue ?? 0 > 0 ||
           (server["request_queue_depth"] as? NSNumber)?.doubleValue ?? 0 > 0 {
            return "MLX is busy; skipping background inference"
        }
        let error = summary["last_error"] as? [String: Any] ?? [:]
        let latest = metrics["latest"] as? [String: Any] ?? [:]
        let message = error["error"] as? String ?? ""
        if message.range(of: "out.?of.?memory|insufficient memory", options: [.regularExpression, .caseInsensitive]) != nil,
           !((latest["timestamp_unix"] as? NSNumber)?.doubleValue ?? -.infinity >
             (error["timestamp_unix"] as? NSNumber)?.doubleValue ?? .infinity) {
            return "MLX reported GPU out of memory; waiting for server recovery"
        }
        return nil
    }
}
#endif
