// Generated by services/dot-relay/generate-native.mjs; do not edit.
import Foundation
enum DotAppearanceRules {
    static let version = 1
    static let portraitSize = 64
    static let glyphSize = 16
    static let sourceBytes = 2097152
    static let sourcePixels = 4194304
    static let portraitBytes = 24576
    static let glyphBytes = 1024
    static let glyphBase64 = 1368
    static let relationBytes = 96
    static let pixelSizeDivisor = 6
    static let pixelMinSize = 7
    static let pixelMargin = 3
    static let pixelYDivisor = 4
    static let panelGlyphSize = 32
    static let paperGlyphSize = 24
    static let matrixGlyphSize = 7
    static let panelMargin = 8
    static let labels = ["AWAITING ACTIVITY", "HOST STOPPED", "WORKING", "NEEDS YOU", "COMPLETED", "FAILED", "OLD REPORT", "UNKNOWN", "NOT LINKED"]
    static let compactLabels = ["Dot", "Stopped", "Working", "Help", "Done", "Failed", "Old", "Unknown", "Unlinked"]
}
struct DotAppearance: Codable, Equatable, Sendable {
    var version: Int; var id: String; var png: String?; var rgba: String
    var glyph: Data? {
        guard version == DotAppearanceRules.version, id.range(of: "^[a-f0-9]{64}$", options: .regularExpression) != nil,
              rgba.utf8.count == DotAppearanceRules.glyphBase64,
              let data = Data(base64Encoded: rgba), data.count == DotAppearanceRules.glyphBytes else { return nil }
        return data
    }
    var portrait: Data? {
        guard glyph != nil, let png, png.utf8.count <= ((DotAppearanceRules.portraitBytes + 2) / 3) * 4,
              let data = Data(base64Encoded: png), data.count <= DotAppearanceRules.portraitBytes,
              data.prefix(8) == Data([137,80,78,71,13,10,26,10]) else { return nil }
        return data
    }
    var compactDictionary: [String: Any]? {
        guard glyph != nil else { return nil }
        return ["version": version, "id": id, "rgba": rgba]
    }
}
struct DotSurfaceRelation: Codable, Sendable {
    var kind: String; var direction: String; var stage: String; var target: String?; var receivedAt: Int; var evidence: String
    var label: String {
        let recipient = target.map { "Unverified " + $0 } ?? "Unknown target"
        let edge = direction == "dot_to_agent" ? "Dot → " + recipient : recipient + " → Dot"
        return kind + " · " + stage + " · " + edge + " · Dot report"
    }
}
struct DotSurfaceSnapshot: Codable, Sendable {
    var configured: Bool = false; var hosting: Bool = false; var authorized: Bool? = nil
    var reportState: String?; var reportedAt: Int?; var expiresAt: Int?
    var code: Int?; var validForMs: Int?; var appearance: DotAppearance?; var relation: DotSurfaceRelation?
    var effectiveCode: Int { phase(at: Int(Date().timeIntervalSince1970 * 1000)) }
    func phase(at now: Int) -> Int {
        guard hosting else { return 1 }
        if authorized == false { return 8 }
        guard let state = reportState else { return 0 }
        guard let stamp = reportedAt, stamp >= 0, stamp <= now else { return 7 }
        if state == "stale" { return 6 }
        if state == "completed" { return 4 }
        if state == "failed" { return 5 }
        guard expiresAt.map({ $0 > now }) ?? true, now - stamp < DotLimits.reportFreshMs else { return 6 }
        return state == "working" ? 2 : state == "needs_attention" ? 3 : 7
    }
    var label: String { DotAppearanceRules.labels[effectiveCode] }
}
