"""Encode three canonical Blender reliefs, with PNG/consumer drift checking."""
from pathlib import Path
import hashlib, sys
from PIL import Image
root=Path(__file__).resolve().parents[2]
for name in ('claude','codex','openclaw'):
    source=Path(__file__).with_name(name+'-relief.png')
    target=root/('esp32/src/ui/widgets/ips10_relief_'+name+'_generated.h')
    image = Image.open(source).convert('RGBA')
    assert image.size == (112, 112)
    color, alpha = bytearray(), bytearray()
    pixels = image.tobytes()
    for i in range(0, len(pixels), 4):
        r, g, b, a = pixels[i:i+4]
        value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        color.extend((value & 255, value >> 8))
        alpha.append(a)
    data = color + alpha
    lines = ['#pragma once', '// Generated by design/ips10/encode_creatures.py. Do not edit.',
             '// Blender source: design/ips10/creatures.py (5.2); input PNG SHA256:',
             '// ' + hashlib.sha256(source.read_bytes()).hexdigest(),
             '#include <lvgl.h>', f'namespace IPS10Relief_{name} {{',
             '// One shared flash image, 36.75 KiB; no runtime allocation or decompression.',
             'alignas(4) static const uint8_t pixels[] = {']
    lines += ['    ' + ','.join(f'0x{b:02x}' for b in data[i:i+24]) + ',' for i in range(0, len(data), 24)]
    lines += ['};', 'static const lv_image_dsc_t image = [] {',
              '    lv_image_dsc_t d{};', '    d.header.magic=LV_IMAGE_HEADER_MAGIC;',
              '    d.header.cf=LV_COLOR_FORMAT_RGB565A8;',
              '    d.header.w=112;d.header.h=112;d.header.stride=224;',
              '    d.data_size=sizeof(pixels);d.data=pixels;return d;', '}();', '}', '']
    result='\n'.join(lines)
    if '--check' in sys.argv: assert target.read_text()==result, name+' relief drift'
    else: target.write_text(result)
print('IPS10 reliefs: PNG/consumer conversion verified')
