"""Encode the generated ocean as a flash-resident LVGL RGB565 image.
Python 3 + Pillow. --check verifies the committed consumer against the PNG.
"""
from pathlib import Path
import hashlib
import sys
from PIL import Image

source = Path(__file__).with_name('ocean.png')
target = source.parents[2] / 'esp32/src/ui/widgets/ips10_ocean_generated.h'
image = Image.open(source).convert('RGBA').resize((640,400), Image.Resampling.LANCZOS)
assert image.size == (640, 400)
color, alpha = bytearray(), bytearray()
pixels = image.tobytes()
for i in range(0, len(pixels), 4):
    r, g, b, a = pixels[i:i+4]
    value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    color.extend((value & 255, value >> 8))
    alpha.append(a)
data = color
lines = ['#pragma once', '// Generated by design/ips10/encode_ocean.py. Do not edit.',
         '// Generated underwater background; input PNG SHA256:',
         '// ' + hashlib.sha256(source.read_bytes()).hexdigest(),
         '#include <lvgl.h>', 'namespace IPS10Ocean {',
         '// One shared flash image, 500 KiB; no runtime allocation or decompression.',
         'alignas(4) static const uint8_t pixels[] = {']
lines += ['    ' + ','.join(f'0x{b:02x}' for b in data[i:i+24]) + ',' for i in range(0, len(data), 24)]
lines += ['};', 'static const lv_image_dsc_t image = [] {',
          '    lv_image_dsc_t d{};', '    d.header.magic=LV_IMAGE_HEADER_MAGIC;',
          '    d.header.cf=LV_COLOR_FORMAT_RGB565;',
          '    d.header.w=640;d.header.h=400;d.header.stride=1280;',
          '    d.data_size=sizeof(pixels);d.data=pixels;return d;', '}();', '}', '']
result = '\n'.join(lines)
if '--check' in sys.argv:
    assert target.read_text() == result, 'Ocean consumer drift: run design/ips10/encode_ocean.py'
    print('IPS10 ocean: PNG and LVGL consumer match')
else:
    target.write_text(result)
