/** Generate native Swift art from the actual Node renderer (no second drawing). */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { MATRIX_RULES, MATRIX_POLICY, MATRIX_AGENTS, MATRIX_KINDS, MATRIX_FACES, UI } from '../shared/src/index.js';
import { MATRIX_COLORS, MATRIX_LAYOUT, MATRIX_GLYPHS, renderMatrixBase, renderMatrixFace, matrixDigit, rgb } from '../bridge/src/pixoo/matrix-art.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export function encodeFrame(frame: Uint8Array): string {
  const packed: number[] = [];
  for (let i = 0; i < frame.length;) {
    let count = 1;
    while (count < 255 && i + count * 3 < frame.length && [0, 1, 2].every(c => frame[i + c] === frame[i + count * 3 + c])) count++;
    packed.push(count, frame[i], frame[i + 1], frame[i + 2]); i += count * 3;
  }
  return Buffer.from(packed).toString('base64');
}
export function swiftMatrixSource(): string {
  const frames: string[] = [];
  // The 11×11 face is keyed by MatrixFace; the 32×32 world by MatrixKind.
  for (const face of MATRIX_FACES) for (let frame = 0; frame < MATRIX_RULES.frames; frame++) {
    frames.push(`        "11/${face}/neutral/${frame}": "${encodeFrame(renderMatrixFace(face, frame))}"`);
  }
  for (const size of [32] as const) for (const kind of MATRIX_KINDS) {
    const glyphs = kind === 'waiting' || kind === 'error' || kind === 'arrival' || kind === 'done' || kind === 'asked' || kind === 'reply'
      ? MATRIX_GLYPHS : ['summary', 'summary-error'];
    for (const glyph of glyphs) for (let frame = 0; frame < MATRIX_RULES.frames; frame++) {
      frames.push(`        "${size}/${kind}/${glyph}/${frame}": "${encodeFrame(renderMatrixBase(size, kind, glyph, frame))}"`);
    }
  }
  const map = (pairs: [string, unknown][]) => `[${pairs.map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(', ')}]`;
  return `// GENERATED by pnpm generate-matrix-expressions. DO NOT EDIT.
// Policy: shared/src/matrix-expression.ts; art: bridge/src/pixoo/matrix-art.ts.
// RLE runs are (pixel count, R, G, B); no external resources or interpreters.
import Foundation

enum MatrixFrames {
${Object.entries(MATRIX_RULES).map(([k, v]) => `    static let ${k} = ${v}`).join('\n')}
${Object.entries(MATRIX_LAYOUT).map(([k, v]) => `    static let ${k} = ${v}`).join('\n')}
    static let awaitingPrefix = ${JSON.stringify(MATRIX_POLICY.awaitingPrefix)}
    static let stateKinds: [String: String] = ${map(Object.entries(MATRIX_POLICY.stateKinds))}
${['resultTypes', 'rejectedStatuses', 'replyTypes', 'askTypes', 'closeTypes', 'priority', 'urgent', 'summaryKinds'].map(k => `    static let ${k}: [String] = ${JSON.stringify(MATRIX_POLICY[k as keyof typeof MATRIX_POLICY])}`).join('\n')}
    static let agents: [String: String] = ${map(Object.entries(MATRIX_AGENTS))}
    static let awaitingFaces: [[String]] = ${JSON.stringify(MATRIX_POLICY.awaitingFaces)}
    static let ciFaces: [String: String] = ${map(MATRIX_POLICY.ciFaces.map(([k, v]) => [k, v]))}
    static let gatewayAgent = ${JSON.stringify(MATRIX_POLICY.gatewayAgent)}
    static let colors: [String: [UInt8]] = ${map(Object.entries(MATRIX_COLORS).map(([k, v]) => [k, rgb(v)]))}
    static let overflow: [UInt8] = ${JSON.stringify(rgb(UI.hudText))}
    static let digits: [String: [Int]] = ${map([..."0123456789+-"].map(d => [d, matrixDigit(d)]))}
    static let encoded: [String: String] = [
${frames.join(',\n')}
    ]
    static func base(size: Int, kind: String, glyph: String, frame: Int) -> [UInt8] {
        let key = "\\(size)/\\(kind)/\\(size == 11 ? "neutral" : glyph)/\\(frame)"
        guard let encoded = encoded[key], let data = Data(base64Encoded: encoded) else {
            return [UInt8](repeating: 0, count: size * size * 3)
        }
        let runs = [UInt8](data)
        var out: [UInt8] = []; out.reserveCapacity(size * size * 3)
        for i in stride(from: 0, to: runs.count, by: 4) {
            for _ in 0..<Int(runs[i]) { out.append(contentsOf: runs[(i + 1)...(i + 3)]) }
        }
        return out
    }
}
`;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const output = path.join(root, 'apple/AgentDeck/Daemon/Modules/MatrixFrames.generated.swift');
  const source = swiftMatrixSource();
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(output, 'utf8') !== source) throw Error('Matrix frame/policy drift; run pnpm generate-matrix-expressions');
  } else fs.writeFileSync(output, source);
}
