import { DOT_LIMITS, DOT_OAUTH_LIMITS, DOT_PRIVATE_MCP } from '../../shared/dist/dot-rules.js';
import { tools, eventDefinition, schemas, VERSION } from './dist/contracts.js';
import { writeFileSync, readFileSync } from 'node:fs';
function emit(file, data) {
  if (process.argv.includes('--check')) {
    if (readFileSync(file, 'utf8') !== data) throw new Error('Dot generated consumer drift: ' + file.pathname);
  } else writeFileSync(file, data);
}
const definitions = { DotLimits: DOT_LIMITS, DotOAuthLimits: DOT_OAUTH_LIMITS, DotPrivateMCP: DOT_PRIVATE_MCP };
const swift = '// Generated by services/dot-relay/generate-native.mjs; do not edit.\n'
  + Object.entries(definitions).map(([name, fields]) => `enum ${name} {\n${Object.entries(fields).map(([key, value]) => `    static let ${key} = ${JSON.stringify(value)}`).join('\n')}\n}`).join('\n') + '\n';
emit(new URL('../../apple/AgentDeck/Daemon/Dot/DotRules.generated.swift', import.meta.url), swift);
emit(new URL('../../apple/AgentDeck/Resources/dot-mcp-contract.json', import.meta.url), JSON.stringify({ version: VERSION, event: eventDefinition, schemas,
  tools: tools.map(({ read, ...t }) => ({ ...t, annotations: { readOnlyHint: read, destructiveHint: false, idempotentHint: true, openWorldHint: false } })) }, null, 2) + '\n');
const { DOT_INTERACTION_RANK, DOT_INTERACTION_TERMINAL } = await import('../../shared/dist/dot-interactions.js');
const relationSwift = `// Generated by services/dot-relay/generate-native.mjs; do not edit.
#if os(macOS)
import Foundation
struct DotInteractionEvent: Codable, Sendable {
    var relationId: String; var sequence: Int; var kind: String; var direction: String; var stage: String
    var targetRef: String?; var summary: String; var evidence: String; var receivedAt: Int
    var dictionary: [String: Any] {
        ["relationId": relationId, "sequence": sequence, "kind": kind, "direction": direction, "stage": stage,
         "targetRef": targetRef as Any? ?? NSNull(), "summary": summary, "evidence": evidence, "receivedAt": receivedAt]
    }
    var label: String {
        let target = targetRef.map { "Unverified target " + $0 } ?? "Unknown target"
        let edge = direction == "dot_to_agent" ? "Dot → " + target : target + " → Dot"
        return kind + " · " + stage + " · " + edge + " · Dot report"
    }
}
enum DotInteractionPolicy {
    static let rank: [String: Int] = [${Object.entries(DOT_INTERACTION_RANK).map(([k,v]) => `"${k}": ${v}`).join(', ')}]
    static let terminal = [${DOT_INTERACTION_TERMINAL.map(s => `"${s}"`).join(', ')}]
    static func allows(_ prior: DotInteractionEvent?, _ next: DotInteractionEvent) -> Bool {
        guard rank[next.stage] != nil else { return false }
        guard let prior else { return true }
        return next.sequence > prior.sequence && next.kind == prior.kind && next.direction == prior.direction
            && next.targetRef == prior.targetRef && !terminal.contains(prior.stage)
            && (rank[next.stage] ?? -1) >= (rank[prior.stage] ?? Int.max)
    }
}
#endif
`;
emit(new URL('../../apple/AgentDeck/Daemon/Dot/DotInteraction.generated.swift', import.meta.url), relationSwift);

const { DOT_APPEARANCE_RULES: A, DOT_PHASES, defaultDotRGBA } = await import('../../shared/dist/dot-appearance.js');
const phaseStrings = DOT_PHASES.map(s => JSON.stringify(s)).join(', ');
const surfaceSwift = `// Generated by services/dot-relay/generate-native.mjs; do not edit.
import Foundation
enum DotAppearanceRules {
${Object.entries(A).map(([k,v]) => `    static let ${k} = ${v}`).join('\n')}
    static let labels = [${phaseStrings}]
}
struct DotAppearance: Codable, Equatable, Sendable {
    var version: Int; var id: String; var png: String?; var rgba: String
    var glyph: Data? {
        guard version == DotAppearanceRules.version, id.range(of: "^[a-f0-9]{64}$", options: .regularExpression) != nil,
              rgba.utf8.count == DotAppearanceRules.glyphBase64,
              let data = Data(base64Encoded: rgba), data.count == DotAppearanceRules.glyphBytes else { return nil }
        return data
    }
    var portrait: Data? {
        guard glyph != nil, let png, png.utf8.count <= ((DotAppearanceRules.portraitBytes + 2) / 3) * 4,
              let data = Data(base64Encoded: png), data.count <= DotAppearanceRules.portraitBytes,
              data.prefix(8) == Data([137,80,78,71,13,10,26,10]) else { return nil }
        return data
    }
    var compactDictionary: [String: Any]? {
        guard glyph != nil else { return nil }
        return ["version": version, "id": id, "rgba": rgba]
    }
}
struct DotSurfaceRelation: Codable, Sendable {
    var kind: String; var direction: String; var stage: String; var target: String?; var receivedAt: Int; var evidence: String
    var label: String {
        let recipient = target.map { "Unverified " + $0 } ?? "Unknown target"
        let edge = direction == "dot_to_agent" ? "Dot → " + recipient : recipient + " → Dot"
        return kind + " · " + stage + " · " + edge + " · Dot report"
    }
}
struct DotSurfaceSnapshot: Codable, Sendable {
    var configured: Bool = false; var hosting: Bool = false
    var reportState: String?; var reportedAt: Int?; var expiresAt: Int?
    var code: Int?; var validForMs: Int?; var appearance: DotAppearance?; var relation: DotSurfaceRelation?
    var effectiveCode: Int { phase(at: Int(Date().timeIntervalSince1970 * 1000)) }
    func phase(at now: Int) -> Int {
        guard hosting else { return 1 }
        guard let state = reportState else { return 0 }
        guard let stamp = reportedAt, stamp >= 0, stamp <= now else { return 7 }
        if state == "stale" { return 6 }
        if state == "completed" { return 4 }
        if state == "failed" { return 5 }
        guard expiresAt.map({ $0 > now }) ?? true, now - stamp < DotLimits.reportFreshMs else { return 6 }
        return state == "working" ? 2 : state == "needs_attention" ? 3 : 7
    }
    var label: String { DotAppearanceRules.labels[effectiveCode] }
}
`;
emit(new URL('../../apple/AgentDeck/Model/DotSurface.generated.swift', import.meta.url), surfaceSwift);
const kotlin = `// Generated by services/dot-relay/generate-native.mjs; do not edit.
package dev.agentdeck.net
import kotlinx.serialization.Serializable
object DotSurfaceRules {
${Object.entries(A).map(([k,v]) => `    const val ${k} = ${v}`).join('\n')}
    const val reportFreshMs = ${DOT_LIMITS.reportFreshMs}L
    const val defaultRgbaBase64 = "${Buffer.from(defaultDotRGBA()).toString("base64")}"
    val labels = listOf(${phaseStrings})
}
@Serializable data class DotAppearance(val version: Int, val id: String, val png: String? = null, val rgba: String) {
    fun validGlyph(): Boolean = version == DotSurfaceRules.version && Regex("[a-f0-9]{64}").matches(id) &&
        rgba.length == DotSurfaceRules.glyphBase64 && Regex("[A-Za-z0-9+/]+==").matches(rgba)
}
@Serializable data class DotSurfaceRelation(val kind: String, val direction: String, val stage: String, val target: String? = null, val receivedAt: Long, val evidence: String) {
    val label: String get() = kind + " · " + stage + " · " + (if (direction == "dot_to_agent") "Dot → " + (target?.let { "Unverified " + it } ?: "Unknown target") else (target?.let { "Unverified " + it } ?: "Unknown target") + " → Dot") + " · Dot report"
}
@Serializable data class DotSurfaceSnapshot(val configured: Boolean = false, val hosting: Boolean = false,
    val reportState: String? = null, val reportedAt: Long? = null, val expiresAt: Long? = null,
    val code: Int? = null, val validForMs: Long? = null, val appearance: DotAppearance? = null, val relation: DotSurfaceRelation? = null) {
    fun effectiveCode(now: Long): Int {
        if (!hosting) return 1
        val state = reportState ?: return 0
        val stamp = reportedAt ?: return 7
        if (stamp < 0 || stamp > now) return 7
        if (state == "stale") return 6
        if (state == "completed") return 4
        if (state == "failed") return 5
        if ((expiresAt != null && expiresAt <= now) || now - stamp >= DotSurfaceRules.reportFreshMs) return 6
        return when (state) { "working" -> 2; "needs_attention" -> 3; else -> 7 }
    }
}
`;
emit(new URL('../../android/app/src/main/kotlin/dev/agentdeck/net/DotSurface.generated.kt', import.meta.url), kotlin);
const cpp = `// Generated by services/dot-relay/generate-native.mjs; do not edit.
#pragma once
#include <stdint.h>
namespace DotSurfaceRules {
${Object.entries(A).map(([k,v]) => `static constexpr uint32_t ${k} = ${v}U;`).join('\n')}
static constexpr uint32_t reportFreshMs = ${DOT_LIMITS.reportFreshMs}U;
static constexpr uint8_t matrixRgba[] = {${Array.from(defaultDotRGBA(A.matrixGlyphSize)).join(",")}};
static constexpr uint8_t defaultRgba[] = {${Array.from(defaultDotRGBA()).join(",")}};
static constexpr const char* labels[] = {${phaseStrings}};
}
`;
emit(new URL('../../esp32/src/state/dot_surface_generated.h', import.meta.url), cpp);
const { DOT_PHASE_COLORS, DOT_STATUS_MARKS, defaultDotRGBA: defaultPixels } = await import('../../shared/dist/dot-appearance.js');
const nativePixel = `// Generated by services/dot-relay/generate-native.mjs; do not edit.
import Foundation
enum DotPixelOverlay {
    static let defaultRgba: [UInt8] = [${Array.from(defaultPixels()).join(',')}]
    static let colors: [[UInt8]] = [${DOT_PHASE_COLORS.map(hex => '[' + [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)).join(',') + ']').join(',')}]
    static let marks: [[String]] = ${JSON.stringify(DOT_STATUS_MARKS)}
    static func paint(_ data: Data, width: Int, dot: DotSurfaceSnapshot?, now: Int = Int(Date().timeIntervalSince1970 * 1000)) -> Data {
        guard width >= 32, data.count == width * width * 3, let dot, dot.configured else { return data }
        var rgb = [UInt8](data), rgba = dot.appearance?.glyph.map { [UInt8]($0) } ?? defaultRgba
        let size = width / 4, x0 = width - size - 2, y0 = 12, tint = colors[dot.phase(at: now)]
        func pixel(_ x: Int, _ y: Int, _ color: [UInt8], _ alpha: Int = 255) {
            guard x >= 0, y >= 0, x < width, y < width else { return }
            let i = (y * width + x) * 3
            for k in 0..<3 { rgb[i+k] = UInt8((Int(color[k]) * alpha + Int(rgb[i+k]) * (255-alpha) + 127) / 255) }
        }
        for y in 0..<size { for x in 0..<size {
            let i = ((y * 16 / size) * 16 + x * 16 / size) * 4
            pixel(x0+x,y0+y,Array(rgba[i..<i+3]),Int(rgba[i+3]))
        } }
        for i in -1...size { pixel(x0+i,y0-1,tint); pixel(x0+i,y0+size,tint) }
        for y in 0..<5 { pixel(x0,y0+size+2+y,tint); pixel(x0+3,y0+size+2+y,tint) }
        for x in 0..<3 { pixel(x0+x,y0+size+2,tint); pixel(x0+x,y0+size+6,tint) }
        for (y,row) in marks[dot.phase(at: now)].enumerated() {
            for (x,bit) in row.enumerated() where bit == "1" { pixel(x0+size-3+x,y0+size+2+y,tint) }
        }
        return Data(rgb)
    }
}
`;
emit(new URL('../../apple/AgentDeck/Model/DotPixels.generated.swift', import.meta.url), nativePixel);
