import { DOT_LIMITS, DOT_OAUTH_LIMITS } from '../../shared/dist/dot-rules.js';
import { tools, eventDefinition, schemas, VERSION } from './dist/contracts.js';
import { writeFileSync } from 'node:fs';
const definitions = { DotLimits: DOT_LIMITS, DotOAuthLimits: DOT_OAUTH_LIMITS };
const swift = '// Generated by services/dot-relay/generate-native.mjs; do not edit.\n#if os(macOS)\n'
  + Object.entries(definitions).map(([name, fields]) => `enum ${name} {\n${Object.entries(fields).map(([key, value]) => `    static let ${key} = ${value}`).join('\n')}\n}`).join('\n') + '\n#endif\n';
writeFileSync(new URL('../../apple/AgentDeck/Daemon/Dot/DotRules.generated.swift', import.meta.url), swift);
writeFileSync(new URL('../../apple/AgentDeck/Resources/dot-mcp-contract.json', import.meta.url), JSON.stringify({ version: VERSION, event: eventDefinition, schemas,
  tools: tools.map(({ read, ...t }) => ({ ...t, annotations: { readOnlyHint: read, destructiveHint: false, idempotentHint: true, openWorldHint: false } })) }, null, 2) + '\n');
const { DOT_INTERACTION_RANK, DOT_INTERACTION_TERMINAL } = await import('../../shared/dist/dot-interactions.js');
const relationSwift = `// Generated by services/dot-relay/generate-native.mjs; do not edit.
#if os(macOS)
import Foundation
struct DotInteractionEvent: Codable, Sendable {
    var relationId: String; var sequence: Int; var kind: String; var direction: String; var stage: String
    var targetRef: String?; var summary: String; var evidence: String; var receivedAt: Int
    var dictionary: [String: Any] {
        ["relationId": relationId, "sequence": sequence, "kind": kind, "direction": direction, "stage": stage,
         "targetRef": targetRef as Any? ?? NSNull(), "summary": summary, "evidence": evidence, "receivedAt": receivedAt]
    }
    var label: String {
        let target = targetRef.map { "Unverified target " + $0 } ?? "Unknown target"
        let edge = direction == "dot_to_agent" ? "Dot → " + target : target + " → Dot"
        return kind + " · " + stage + " · " + edge + " · Dot report"
    }
}
enum DotInteractionPolicy {
    static let rank: [String: Int] = [${Object.entries(DOT_INTERACTION_RANK).map(([k,v]) => `"${k}": ${v}`).join(', ')}]
    static let terminal = [${DOT_INTERACTION_TERMINAL.map(s => `"${s}"`).join(', ')}]
    static func allows(_ prior: DotInteractionEvent?, _ next: DotInteractionEvent) -> Bool {
        guard rank[next.stage] != nil else { return false }
        guard let prior else { return true }
        return next.sequence > prior.sequence && next.kind == prior.kind && next.direction == prior.direction
            && next.targetRef == prior.targetRef && !terminal.contains(prior.stage)
            && (rank[next.stage] ?? -1) >= (rank[prior.stage] ?? Int.max)
    }
}
#endif
`;
writeFileSync(new URL('../../apple/AgentDeck/Daemon/Dot/DotInteraction.generated.swift', import.meta.url), relationSwift);
