/** MLX inference is allowed to use a resident model, never to select a download.
 * A catalog-only server must advertise exactly one model. A user pin constrains
 * that choice; it is not permission for background work to hot-swap a server.
 * Swift policy is generated by scripts/generate-mlx-safety.mjs. */
export const MLX_SAFETY = { cooldownMs: 300_000, probeTimeoutMs: 2_000, maxEndpoints: 64 } as const;

export function mlxBaseUrl(endpoint: string): string {
  const url = new URL(endpoint);
  if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) {
    throw new Error('MLX endpoint must be an HTTP(S) URL without credentials, query or fragment');
  }
  url.pathname = url.pathname.replace(/\/+$/, '').replace(/\/(?:v1\/)?chat\/completions$/, '').replace(/\/v1$/, '');
  return url.href.replace(/\/$/, '');
}

export function mlxModelPin(value: unknown): string | null {
  return typeof value === 'string' && !['', 'default', 'qwen3-30b'].includes(value.trim()) ? value.trim() : null;
}

export function selectMlxModel(loadedKnown: boolean, loaded: string | null, catalog: string[], pin?: string | null): string {
  const models = [...new Set(catalog.map(m => m.trim()).filter(Boolean))];
  const model = loadedKnown ? mlxModelPin(loaded) : models.length === 1 ? models[0] : null;
  if (!model || model.toLowerCase().includes('nanollava')) throw new Error('MLX has no unambiguous resident chat model');
  const requested = mlxModelPin(pin);
  if (requested && requested !== model) throw new Error(`MLX model mismatch: requested ${requested}, resident ${model}; refusing model replacement`);
  return model;
}

type ObjectValue = Record<string, unknown>;
function object(value: unknown): ObjectValue {
  return value !== null && typeof value === 'object' && !Array.isArray(value) ? value as ObjectValue : {};
}

/** Read-only checks. A VLM metrics OOM cannot be cleared by /health=healthy. */
export function mlxMetricsProblem(value: unknown): string | null {
  const metrics = object(value), summary = object(metrics.summary), server = object(metrics.server);
  if (Number(summary.in_flight) > 0 || Number(server.request_queue_depth) > 0) return 'MLX is busy; skipping background inference';
  const error = object(summary.last_error), latest = object(metrics.latest);
  if (/out.?of.?memory|insufficient memory/i.test(String(error.error ?? '')) &&
      !(Number(latest.timestamp_unix) > Number(error.timestamp_unix))) {
    return 'MLX reported GPU out of memory; waiting for server recovery';
  }
  return null;
}

async function readProbe(url: string): Promise<{ status: number; body: ObjectValue }> {
  const response = await fetch(url, { signal: AbortSignal.timeout(MLX_SAFETY.probeTimeoutMs) });
  if (response.status === 404 || response.status === 405) { await response.body?.cancel(); return { status: response.status, body: {} }; }
  if (!response.ok) { await response.body?.cancel(); throw new Error(`MLX safety probe HTTP ${response.status}`); }
  return { status: response.status, body: object(await response.json()) };
}

export async function resolveSafeMlxModel(endpoint: string, pin?: string | null): Promise<string> {
  const base = mlxBaseUrl(endpoint);
  const health = await readProbe(`${base}/health`);
  if (Object.hasOwn(health.body, 'loaded_model')) {
    const model = selectMlxModel(true, typeof health.body.loaded_model === 'string' ? health.body.loaded_model : null, [], pin);
    const metrics = await readProbe(`${base}/metrics`);
    const problem = mlxMetricsProblem(metrics.body);
    if (problem) throw new Error(problem);
    return model;
  }
  for (const path of ['/v1/models', '/models']) {
    const response = await readProbe(base + path);
    if (response.status === 404 || response.status === 405) continue;
    const rows = Array.isArray(response.body.data) ? response.body.data : [];
    return selectMlxModel(false, null, rows.map(row => object(row).id).filter((id): id is string => typeof id === 'string'), pin);
  }
  throw new Error('MLX resident model could not be verified');
}

const endpoints = new Map<string, { active: boolean; until: number }>();
export function clearMlxSafetyForTests(): void { endpoints.clear(); }

/** Fail-fast admission, fresh resident-model check and body-inclusive timeout.
 * The server may ignore HTTP cancellation, so timeouts/5xx/429 quarantine the
 * endpoint. No queue, and no concurrent judge/classifier/summarizer/probe posts.
 * Cross-process admission ultimately belongs to the server: VLM metrics are an
 * additional check, not an atomic reservation against unrelated clients. */
export async function guardedMlxFetch(endpoint: string, init: RequestInit): Promise<Response> {
  const base = mlxBaseUrl(endpoint), now = Date.now();
  for (const [key, entry] of endpoints) if (!entry.active && entry.until <= now) endpoints.delete(key);
  const old = endpoints.get(base);
  if (old?.active || (old && old.until > now)) throw new Error('MLX inference paused: busy or recovering from a failed request');
  if (endpoints.size >= MLX_SAFETY.maxEndpoints) throw new Error('MLX endpoint admission limit reached');
  const entry = { active: true, until: 0 };
  endpoints.set(base, entry);
  let posted = false;
  try {
    if (typeof init.body !== 'string') throw new Error('MLX requires a JSON request body');
    const body = object(JSON.parse(init.body));
    body.model = await resolveSafeMlxModel(base, mlxModelPin(body.model));
    init.signal?.throwIfAborted();
    posted = true;
    const response = await fetch(`${base}/chat/completions`, { ...init, method: 'POST', body: JSON.stringify(body),
      signal: init.signal ?? AbortSignal.timeout(90_000) });
    // Hold admission until the BODY ends, not just until HTTP headers arrive.
    const data = await response.arrayBuffer();
    if (response.status >= 500 || response.status === 429) entry.until = Date.now() + MLX_SAFETY.cooldownMs;
    return new Response(response.status === 204 || response.status === 205 || response.status === 304 ? null : data,
      { status: response.status, statusText: response.statusText, headers: response.headers });
  } catch (error) {
    if (posted) entry.until = Date.now() + MLX_SAFETY.cooldownMs;
    throw error;
  } finally { entry.active = false; }
}
