import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

export const HERMES_PLUGIN_NAME = 'agentdeck-observer';

export interface HermesInstallOptions {
  home?: string;
}

export interface HermesInstallResult {
  installed: boolean;
  reason?: string;
  warning?: string;
  pluginPath: string;
}

export function hermesPluginPath(home = homedir()): string {
  return join(home, '.hermes', 'plugins', HERMES_PLUGIN_NAME);
}

export function hermesPluginManifest(): string {
  return `name: ${HERMES_PLUGIN_NAME}\nversion: "1.0"\ndescription: "AgentDeck session observer"\n`;
}

/**
 * Hermes loads this plugin in its own Python process. The observer uses only
 * the standard library, bounds its loopback request, and never changes a hook
 * result, so an unavailable AgentDeck daemon cannot affect Hermes execution.
 */
export function hermesPluginSource(): string {
  return `"""AgentDeck observer plugin — generated by @agentdeck/hooks."""
import json
import os
from pathlib import Path
from urllib.request import Request, urlopen

def _port():
    explicit = os.environ.get("AGENTDECK_PORT")
    if explicit and explicit.isdigit() and 1 <= int(explicit) <= 65535:
        return explicit
    try:
        data = json.loads((Path.home() / ".agentdeck" / "daemon.json").read_text())
        value = data.get("httpPort") or data.get("port")
        if isinstance(value, int) and 1 <= value <= 65535:
            return str(value)
    except Exception:
        pass
    return "9120"

def _post(event, payload):
    body = json.dumps(payload, default=str).encode("utf-8")
    request = Request(
        "http://127.0.0.1:%s/hooks/%s" % (_port(), event),
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=0.8):
            pass
    except Exception:
        pass

def _base(kwargs):
    return {
        "session_id": kwargs.get("session_id") or kwargs.get("task_id") or "",
        "cwd": kwargs.get("cwd") or "",
        "model": kwargs.get("model") or "",
        "platform": kwargs.get("platform") or "",
    }

def _last_user_message(messages):
    if not isinstance(messages, list):
        return ""
    for message in reversed(messages):
        if not isinstance(message, dict) or message.get("role") != "user":
            continue
        content = message.get("content", "")
        if isinstance(content, str):
            return content
        return json.dumps(content, default=str)
    return ""

def register(ctx):
    def session_start(*args, **kwargs):
        data = _base(kwargs)
        if args and not data["session_id"]:
            data["session_id"] = str(args[0])
        _post("hermes_session_start", data)

    def prompt(*args, **kwargs):
        data = _base(kwargs)
        messages = kwargs.get("messages") or (args[0] if args else None)
        data["prompt"] = kwargs.get("user_message") or kwargs.get("prompt") or _last_user_message(messages)
        _post("hermes_user_prompt_submit", data)

    def tool_start(*args, **kwargs):
        data = _base(kwargs)
        data["tool_name"] = kwargs.get("tool_name") or (args[0] if args else "")
        _post("hermes_tool_start", data)

    def tool_end(*args, **kwargs):
        data = _base(kwargs)
        data["tool_name"] = kwargs.get("tool_name") or (args[0] if args else "")
        _post("hermes_tool_end", data)

    def completed(*args, **kwargs):
        _post("hermes_stop", _base(kwargs))

    def turn_end(*args, **kwargs):
        data = _base(kwargs)
        if args and not data["session_id"]:
            data["session_id"] = str(args[0])
        _post("hermes_stop", data)

    def session_finalize(*args, **kwargs):
        data = _base(kwargs)
        if args and not data["session_id"]:
            data["session_id"] = str(args[0])
        _post("hermes_session_end", data)

    ctx.register_hook("on_session_start", session_start)
    ctx.register_hook("pre_llm_call", prompt)
    ctx.register_hook("pre_tool_call", tool_start)
    ctx.register_hook("post_tool_call", tool_end)
    ctx.register_hook("post_llm_call", completed)
    ctx.register_hook("on_session_end", turn_end)
    ctx.register_hook("on_session_finalize", session_finalize)
`;
}

function enableHermesPlugin(home: string): string | undefined {
  const executable = process.env.HERMES_BIN || join(home, '.local', 'bin', 'hermes');
  if (!existsSync(executable)) {
    return 'Hermes executable not found; enable agentdeck-observer with `hermes plugins enable agentdeck-observer`.';
  }
  try {
    execFileSync(executable, ['plugins', 'enable', HERMES_PLUGIN_NAME], {
      stdio: 'ignore',
      timeout: 10_000,
    });
  } catch {
    return 'Plugin files were installed, but Hermes could not enable them automatically; run `hermes plugins enable agentdeck-observer`.';
  }
  return undefined;
}

export function installHermesHooksIfNeeded(opts: HermesInstallOptions = {}): HermesInstallResult {
  const home = opts.home ?? homedir();
  const pluginPath = hermesPluginPath(home);
  if (process.env.AGENTDECK_NO_HERMES_HOOKS === '1') {
    return { installed: false, reason: 'disabled by AGENTDECK_NO_HERMES_HOOKS', pluginPath };
  }

  const manifest = hermesPluginManifest();
  const source = hermesPluginSource();
  const manifestPath = join(pluginPath, 'plugin.yaml');
  const sourcePath = join(pluginPath, '__init__.py');
  if (
    existsSync(manifestPath) &&
    existsSync(sourcePath) &&
    readFileSync(manifestPath, 'utf8') === manifest &&
    readFileSync(sourcePath, 'utf8') === source
  ) {
    return {
      installed: false,
      reason: 'already current',
      warning: enableHermesPlugin(home),
      pluginPath,
    };
  }

  mkdirSync(pluginPath, { recursive: true });
  writeFileSync(manifestPath, manifest, 'utf8');
  writeFileSync(sourcePath, source, 'utf8');
  return { installed: true, warning: enableHermesPlugin(home), pluginPath };
}

export function uninstallHermesHooks(opts: HermesInstallOptions = {}): void {
  rmSync(hermesPluginPath(opts.home), { recursive: true, force: true });
}
